// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_other

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Reward struct {
	Code                 string   `protobuf:"bytes,1,opt,name=code,proto3" json:"code,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Reward) Reset()         { *m = Reward{} }
func (m *Reward) String() string { return proto.CompactTextString(m) }
func (*Reward) ProtoMessage()    {}
func (*Reward) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Reward) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Reward.Unmarshal(m, b)
}
func (m *Reward) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Reward.Marshal(b, m, deterministic)
}
func (m *Reward) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Reward.Merge(m, src)
}
func (m *Reward) XXX_Size() int {
	return xxx_messageInfo_Reward.Size(m)
}
func (m *Reward) XXX_DiscardUnknown() {
	xxx_messageInfo_Reward.DiscardUnknown(m)
}

var xxx_messageInfo_Reward proto.InternalMessageInfo

func (m *Reward) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *Reward) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type AchievementRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AchievementRequest) Reset()         { *m = AchievementRequest{} }
func (m *AchievementRequest) String() string { return proto.CompactTextString(m) }
func (*AchievementRequest) ProtoMessage()    {}
func (*AchievementRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *AchievementRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AchievementRequest.Unmarshal(m, b)
}
func (m *AchievementRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AchievementRequest.Marshal(b, m, deterministic)
}
func (m *AchievementRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AchievementRequest.Merge(m, src)
}
func (m *AchievementRequest) XXX_Size() int {
	return xxx_messageInfo_AchievementRequest.Size(m)
}
func (m *AchievementRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_AchievementRequest.DiscardUnknown(m)
}

var xxx_messageInfo_AchievementRequest proto.InternalMessageInfo

func (m *AchievementRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *AchievementRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type AchievementResponse struct {
	Reward               []*Reward `protobuf:"bytes,1,rep,name=reward,proto3" json:"reward,omitempty"`
	NextNumber           string    `protobuf:"bytes,2,opt,name=nextNumber,proto3" json:"nextNumber,omitempty"`
	Name                 string    `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	ConditionA           string    `protobuf:"bytes,4,opt,name=conditionA,proto3" json:"conditionA,omitempty"`
	ConditionB           string    `protobuf:"bytes,5,opt,name=conditionB,proto3" json:"conditionB,omitempty"`
	Errno                string    `protobuf:"bytes,6,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string    `protobuf:"bytes,7,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}  `json:"-"`
	XXX_unrecognized     []byte    `json:"-"`
	XXX_sizecache        int32     `json:"-"`
}

func (m *AchievementResponse) Reset()         { *m = AchievementResponse{} }
func (m *AchievementResponse) String() string { return proto.CompactTextString(m) }
func (*AchievementResponse) ProtoMessage()    {}
func (*AchievementResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *AchievementResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AchievementResponse.Unmarshal(m, b)
}
func (m *AchievementResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AchievementResponse.Marshal(b, m, deterministic)
}
func (m *AchievementResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AchievementResponse.Merge(m, src)
}
func (m *AchievementResponse) XXX_Size() int {
	return xxx_messageInfo_AchievementResponse.Size(m)
}
func (m *AchievementResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_AchievementResponse.DiscardUnknown(m)
}

var xxx_messageInfo_AchievementResponse proto.InternalMessageInfo

func (m *AchievementResponse) GetReward() []*Reward {
	if m != nil {
		return m.Reward
	}
	return nil
}

func (m *AchievementResponse) GetNextNumber() string {
	if m != nil {
		return m.NextNumber
	}
	return ""
}

func (m *AchievementResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *AchievementResponse) GetConditionA() string {
	if m != nil {
		return m.ConditionA
	}
	return ""
}

func (m *AchievementResponse) GetConditionB() string {
	if m != nil {
		return m.ConditionB
	}
	return ""
}

func (m *AchievementResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *AchievementResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type Box struct {
	Type                 string   `protobuf:"bytes,1,opt,name=type,proto3" json:"type,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=number,proto3" json:"number,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Box) Reset()         { *m = Box{} }
func (m *Box) String() string { return proto.CompactTextString(m) }
func (*Box) ProtoMessage()    {}
func (*Box) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *Box) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Box.Unmarshal(m, b)
}
func (m *Box) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Box.Marshal(b, m, deterministic)
}
func (m *Box) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Box.Merge(m, src)
}
func (m *Box) XXX_Size() int {
	return xxx_messageInfo_Box.Size(m)
}
func (m *Box) XXX_DiscardUnknown() {
	xxx_messageInfo_Box.DiscardUnknown(m)
}

var xxx_messageInfo_Box proto.InternalMessageInfo

func (m *Box) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *Box) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *Box) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

type TreasureMap struct {
	State                string   `protobuf:"bytes,1,opt,name=state,proto3" json:"state,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Url                  string   `protobuf:"bytes,3,opt,name=url,proto3" json:"url,omitempty"`
	Reward               []*Box   `protobuf:"bytes,4,rep,name=reward,proto3" json:"reward,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreasureMap) Reset()         { *m = TreasureMap{} }
func (m *TreasureMap) String() string { return proto.CompactTextString(m) }
func (*TreasureMap) ProtoMessage()    {}
func (*TreasureMap) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *TreasureMap) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreasureMap.Unmarshal(m, b)
}
func (m *TreasureMap) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreasureMap.Marshal(b, m, deterministic)
}
func (m *TreasureMap) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreasureMap.Merge(m, src)
}
func (m *TreasureMap) XXX_Size() int {
	return xxx_messageInfo_TreasureMap.Size(m)
}
func (m *TreasureMap) XXX_DiscardUnknown() {
	xxx_messageInfo_TreasureMap.DiscardUnknown(m)
}

var xxx_messageInfo_TreasureMap proto.InternalMessageInfo

func (m *TreasureMap) GetState() string {
	if m != nil {
		return m.State
	}
	return ""
}

func (m *TreasureMap) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *TreasureMap) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *TreasureMap) GetReward() []*Box {
	if m != nil {
		return m.Reward
	}
	return nil
}

type TreasureMapRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Iv                   string   `protobuf:"bytes,2,opt,name=iv,proto3" json:"iv,omitempty"`
	Data                 string   `protobuf:"bytes,3,opt,name=data,proto3" json:"data,omitempty"`
	Code                 string   `protobuf:"bytes,4,opt,name=code,proto3" json:"code,omitempty"`
	Shareskey            string   `protobuf:"bytes,5,opt,name=shareskey,proto3" json:"shareskey,omitempty"`
	Url                  string   `protobuf:"bytes,6,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *TreasureMapRequest) Reset()         { *m = TreasureMapRequest{} }
func (m *TreasureMapRequest) String() string { return proto.CompactTextString(m) }
func (*TreasureMapRequest) ProtoMessage()    {}
func (*TreasureMapRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *TreasureMapRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreasureMapRequest.Unmarshal(m, b)
}
func (m *TreasureMapRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreasureMapRequest.Marshal(b, m, deterministic)
}
func (m *TreasureMapRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreasureMapRequest.Merge(m, src)
}
func (m *TreasureMapRequest) XXX_Size() int {
	return xxx_messageInfo_TreasureMapRequest.Size(m)
}
func (m *TreasureMapRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_TreasureMapRequest.DiscardUnknown(m)
}

var xxx_messageInfo_TreasureMapRequest proto.InternalMessageInfo

func (m *TreasureMapRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *TreasureMapRequest) GetIv() string {
	if m != nil {
		return m.Iv
	}
	return ""
}

func (m *TreasureMapRequest) GetData() string {
	if m != nil {
		return m.Data
	}
	return ""
}

func (m *TreasureMapRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *TreasureMapRequest) GetShareskey() string {
	if m != nil {
		return m.Shareskey
	}
	return ""
}

func (m *TreasureMapRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type TreasureMapResponse struct {
	Maplist              []*TreasureMap `protobuf:"bytes,1,rep,name=maplist,proto3" json:"maplist,omitempty"`
	Goldtime             string         `protobuf:"bytes,2,opt,name=goldtime,proto3" json:"goldtime,omitempty"`
	Name                 string         `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	Errno                string         `protobuf:"bytes,4,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string         `protobuf:"bytes,5,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{}       `json:"-"`
	XXX_unrecognized     []byte         `json:"-"`
	XXX_sizecache        int32          `json:"-"`
}

func (m *TreasureMapResponse) Reset()         { *m = TreasureMapResponse{} }
func (m *TreasureMapResponse) String() string { return proto.CompactTextString(m) }
func (*TreasureMapResponse) ProtoMessage()    {}
func (*TreasureMapResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *TreasureMapResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_TreasureMapResponse.Unmarshal(m, b)
}
func (m *TreasureMapResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_TreasureMapResponse.Marshal(b, m, deterministic)
}
func (m *TreasureMapResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_TreasureMapResponse.Merge(m, src)
}
func (m *TreasureMapResponse) XXX_Size() int {
	return xxx_messageInfo_TreasureMapResponse.Size(m)
}
func (m *TreasureMapResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_TreasureMapResponse.DiscardUnknown(m)
}

var xxx_messageInfo_TreasureMapResponse proto.InternalMessageInfo

func (m *TreasureMapResponse) GetMaplist() []*TreasureMap {
	if m != nil {
		return m.Maplist
	}
	return nil
}

func (m *TreasureMapResponse) GetGoldtime() string {
	if m != nil {
		return m.Goldtime
	}
	return ""
}

func (m *TreasureMapResponse) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *TreasureMapResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *TreasureMapResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type New struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	GetStatus            string   `protobuf:"bytes,3,opt,name=GetStatus,proto3" json:"GetStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *New) Reset()         { *m = New{} }
func (m *New) String() string { return proto.CompactTextString(m) }
func (*New) ProtoMessage()    {}
func (*New) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *New) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_New.Unmarshal(m, b)
}
func (m *New) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_New.Marshal(b, m, deterministic)
}
func (m *New) XXX_Merge(src proto.Message) {
	xxx_messageInfo_New.Merge(m, src)
}
func (m *New) XXX_Size() int {
	return xxx_messageInfo_New.Size(m)
}
func (m *New) XXX_DiscardUnknown() {
	xxx_messageInfo_New.DiscardUnknown(m)
}

var xxx_messageInfo_New proto.InternalMessageInfo

func (m *New) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *New) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *New) GetGetStatus() string {
	if m != nil {
		return m.GetStatus
	}
	return ""
}

//拉取邀请新人列表服务参数
type PullNewRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullNewRequest) Reset()         { *m = PullNewRequest{} }
func (m *PullNewRequest) String() string { return proto.CompactTextString(m) }
func (*PullNewRequest) ProtoMessage()    {}
func (*PullNewRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *PullNewRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullNewRequest.Unmarshal(m, b)
}
func (m *PullNewRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullNewRequest.Marshal(b, m, deterministic)
}
func (m *PullNewRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullNewRequest.Merge(m, src)
}
func (m *PullNewRequest) XXX_Size() int {
	return xxx_messageInfo_PullNewRequest.Size(m)
}
func (m *PullNewRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullNewRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullNewRequest proto.InternalMessageInfo

func (m *PullNewRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

type PullNewResponse struct {
	Newlist              []*New   `protobuf:"bytes,1,rep,name=newlist,proto3" json:"newlist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullNewResponse) Reset()         { *m = PullNewResponse{} }
func (m *PullNewResponse) String() string { return proto.CompactTextString(m) }
func (*PullNewResponse) ProtoMessage()    {}
func (*PullNewResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *PullNewResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullNewResponse.Unmarshal(m, b)
}
func (m *PullNewResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullNewResponse.Marshal(b, m, deterministic)
}
func (m *PullNewResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullNewResponse.Merge(m, src)
}
func (m *PullNewResponse) XXX_Size() int {
	return xxx_messageInfo_PullNewResponse.Size(m)
}
func (m *PullNewResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullNewResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullNewResponse proto.InternalMessageInfo

func (m *PullNewResponse) GetNewlist() []*New {
	if m != nil {
		return m.Newlist
	}
	return nil
}

func (m *PullNewResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *PullNewResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//灯助力服务参数
type LampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Shareskey            string   `protobuf:"bytes,2,opt,name=shareskey,proto3" json:"shareskey,omitempty"`
	Sharetime            string   `protobuf:"bytes,3,opt,name=sharetime,proto3" json:"sharetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LampRequest) Reset()         { *m = LampRequest{} }
func (m *LampRequest) String() string { return proto.CompactTextString(m) }
func (*LampRequest) ProtoMessage()    {}
func (*LampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *LampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LampRequest.Unmarshal(m, b)
}
func (m *LampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LampRequest.Marshal(b, m, deterministic)
}
func (m *LampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LampRequest.Merge(m, src)
}
func (m *LampRequest) XXX_Size() int {
	return xxx_messageInfo_LampRequest.Size(m)
}
func (m *LampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LampRequest proto.InternalMessageInfo

func (m *LampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *LampRequest) GetShareskey() string {
	if m != nil {
		return m.Shareskey
	}
	return ""
}

func (m *LampRequest) GetSharetime() string {
	if m != nil {
		return m.Sharetime
	}
	return ""
}

type LampResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LampResponse) Reset()         { *m = LampResponse{} }
func (m *LampResponse) String() string { return proto.CompactTextString(m) }
func (*LampResponse) ProtoMessage()    {}
func (*LampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{11}
}

func (m *LampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LampResponse.Unmarshal(m, b)
}
func (m *LampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LampResponse.Marshal(b, m, deterministic)
}
func (m *LampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LampResponse.Merge(m, src)
}
func (m *LampResponse) XXX_Size() int {
	return xxx_messageInfo_LampResponse.Size(m)
}
func (m *LampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LampResponse proto.InternalMessageInfo

func (m *LampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *LampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//获取灯助力列表服务参数
type LamplestRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LamplestRequest) Reset()         { *m = LamplestRequest{} }
func (m *LamplestRequest) String() string { return proto.CompactTextString(m) }
func (*LamplestRequest) ProtoMessage()    {}
func (*LamplestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{12}
}

func (m *LamplestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LamplestRequest.Unmarshal(m, b)
}
func (m *LamplestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LamplestRequest.Marshal(b, m, deterministic)
}
func (m *LamplestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LamplestRequest.Merge(m, src)
}
func (m *LamplestRequest) XXX_Size() int {
	return xxx_messageInfo_LamplestRequest.Size(m)
}
func (m *LamplestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LamplestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LamplestRequest proto.InternalMessageInfo

func (m *LamplestRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *LamplestRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

type LamplestResponse struct {
	Newlist              []*New   `protobuf:"bytes,1,rep,name=newlist,proto3" json:"newlist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LamplestResponse) Reset()         { *m = LamplestResponse{} }
func (m *LamplestResponse) String() string { return proto.CompactTextString(m) }
func (*LamplestResponse) ProtoMessage()    {}
func (*LamplestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{13}
}

func (m *LamplestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LamplestResponse.Unmarshal(m, b)
}
func (m *LamplestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LamplestResponse.Marshal(b, m, deterministic)
}
func (m *LamplestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LamplestResponse.Merge(m, src)
}
func (m *LamplestResponse) XXX_Size() int {
	return xxx_messageInfo_LamplestResponse.Size(m)
}
func (m *LamplestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LamplestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LamplestResponse proto.InternalMessageInfo

func (m *LamplestResponse) GetNewlist() []*New {
	if m != nil {
		return m.Newlist
	}
	return nil
}

func (m *LamplestResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *LamplestResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//体力卡包助力服务参数
type StrengthRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Shareskey            string   `protobuf:"bytes,2,opt,name=shareskey,proto3" json:"shareskey,omitempty"`
	Sharetime            string   `protobuf:"bytes,3,opt,name=sharetime,proto3" json:"sharetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrengthRequest) Reset()         { *m = StrengthRequest{} }
func (m *StrengthRequest) String() string { return proto.CompactTextString(m) }
func (*StrengthRequest) ProtoMessage()    {}
func (*StrengthRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{14}
}

func (m *StrengthRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrengthRequest.Unmarshal(m, b)
}
func (m *StrengthRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrengthRequest.Marshal(b, m, deterministic)
}
func (m *StrengthRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrengthRequest.Merge(m, src)
}
func (m *StrengthRequest) XXX_Size() int {
	return xxx_messageInfo_StrengthRequest.Size(m)
}
func (m *StrengthRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StrengthRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StrengthRequest proto.InternalMessageInfo

func (m *StrengthRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *StrengthRequest) GetShareskey() string {
	if m != nil {
		return m.Shareskey
	}
	return ""
}

func (m *StrengthRequest) GetSharetime() string {
	if m != nil {
		return m.Sharetime
	}
	return ""
}

type StrengthResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrengthResponse) Reset()         { *m = StrengthResponse{} }
func (m *StrengthResponse) String() string { return proto.CompactTextString(m) }
func (*StrengthResponse) ProtoMessage()    {}
func (*StrengthResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{15}
}

func (m *StrengthResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrengthResponse.Unmarshal(m, b)
}
func (m *StrengthResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrengthResponse.Marshal(b, m, deterministic)
}
func (m *StrengthResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrengthResponse.Merge(m, src)
}
func (m *StrengthResponse) XXX_Size() int {
	return xxx_messageInfo_StrengthResponse.Size(m)
}
func (m *StrengthResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StrengthResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StrengthResponse proto.InternalMessageInfo

func (m *StrengthResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *StrengthResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//获取体力助力列表服务参数
type StrelestRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrelestRequest) Reset()         { *m = StrelestRequest{} }
func (m *StrelestRequest) String() string { return proto.CompactTextString(m) }
func (*StrelestRequest) ProtoMessage()    {}
func (*StrelestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{16}
}

func (m *StrelestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrelestRequest.Unmarshal(m, b)
}
func (m *StrelestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrelestRequest.Marshal(b, m, deterministic)
}
func (m *StrelestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrelestRequest.Merge(m, src)
}
func (m *StrelestRequest) XXX_Size() int {
	return xxx_messageInfo_StrelestRequest.Size(m)
}
func (m *StrelestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_StrelestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_StrelestRequest proto.InternalMessageInfo

func (m *StrelestRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *StrelestRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type StrelestResponse struct {
	Newlist              []*New   `protobuf:"bytes,1,rep,name=newlist,proto3" json:"newlist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *StrelestResponse) Reset()         { *m = StrelestResponse{} }
func (m *StrelestResponse) String() string { return proto.CompactTextString(m) }
func (*StrelestResponse) ProtoMessage()    {}
func (*StrelestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{17}
}

func (m *StrelestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_StrelestResponse.Unmarshal(m, b)
}
func (m *StrelestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_StrelestResponse.Marshal(b, m, deterministic)
}
func (m *StrelestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_StrelestResponse.Merge(m, src)
}
func (m *StrelestResponse) XXX_Size() int {
	return xxx_messageInfo_StrelestResponse.Size(m)
}
func (m *StrelestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_StrelestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_StrelestResponse proto.InternalMessageInfo

func (m *StrelestResponse) GetNewlist() []*New {
	if m != nil {
		return m.Newlist
	}
	return nil
}

func (m *StrelestResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *StrelestResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//钻石卡包助力服务参数
type DiamondRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Shareskey            string   `protobuf:"bytes,2,opt,name=shareskey,proto3" json:"shareskey,omitempty"`
	Sharetime            string   `protobuf:"bytes,3,opt,name=sharetime,proto3" json:"sharetime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamondRequest) Reset()         { *m = DiamondRequest{} }
func (m *DiamondRequest) String() string { return proto.CompactTextString(m) }
func (*DiamondRequest) ProtoMessage()    {}
func (*DiamondRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{18}
}

func (m *DiamondRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamondRequest.Unmarshal(m, b)
}
func (m *DiamondRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamondRequest.Marshal(b, m, deterministic)
}
func (m *DiamondRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamondRequest.Merge(m, src)
}
func (m *DiamondRequest) XXX_Size() int {
	return xxx_messageInfo_DiamondRequest.Size(m)
}
func (m *DiamondRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamondRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiamondRequest proto.InternalMessageInfo

func (m *DiamondRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *DiamondRequest) GetShareskey() string {
	if m != nil {
		return m.Shareskey
	}
	return ""
}

func (m *DiamondRequest) GetSharetime() string {
	if m != nil {
		return m.Sharetime
	}
	return ""
}

type DiamondResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamondResponse) Reset()         { *m = DiamondResponse{} }
func (m *DiamondResponse) String() string { return proto.CompactTextString(m) }
func (*DiamondResponse) ProtoMessage()    {}
func (*DiamondResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{19}
}

func (m *DiamondResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamondResponse.Unmarshal(m, b)
}
func (m *DiamondResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamondResponse.Marshal(b, m, deterministic)
}
func (m *DiamondResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamondResponse.Merge(m, src)
}
func (m *DiamondResponse) XXX_Size() int {
	return xxx_messageInfo_DiamondResponse.Size(m)
}
func (m *DiamondResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamondResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiamondResponse proto.InternalMessageInfo

func (m *DiamondResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *DiamondResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//获取钻石助力列表服务参数
type DiamlestRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamlestRequest) Reset()         { *m = DiamlestRequest{} }
func (m *DiamlestRequest) String() string { return proto.CompactTextString(m) }
func (*DiamlestRequest) ProtoMessage()    {}
func (*DiamlestRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{20}
}

func (m *DiamlestRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamlestRequest.Unmarshal(m, b)
}
func (m *DiamlestRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamlestRequest.Marshal(b, m, deterministic)
}
func (m *DiamlestRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamlestRequest.Merge(m, src)
}
func (m *DiamlestRequest) XXX_Size() int {
	return xxx_messageInfo_DiamlestRequest.Size(m)
}
func (m *DiamlestRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamlestRequest.DiscardUnknown(m)
}

var xxx_messageInfo_DiamlestRequest proto.InternalMessageInfo

func (m *DiamlestRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *DiamlestRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type DiamlestResponse struct {
	Newlist              []*New   `protobuf:"bytes,1,rep,name=newlist,proto3" json:"newlist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamlestResponse) Reset()         { *m = DiamlestResponse{} }
func (m *DiamlestResponse) String() string { return proto.CompactTextString(m) }
func (*DiamlestResponse) ProtoMessage()    {}
func (*DiamlestResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{21}
}

func (m *DiamlestResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamlestResponse.Unmarshal(m, b)
}
func (m *DiamlestResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamlestResponse.Marshal(b, m, deterministic)
}
func (m *DiamlestResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamlestResponse.Merge(m, src)
}
func (m *DiamlestResponse) XXX_Size() int {
	return xxx_messageInfo_DiamlestResponse.Size(m)
}
func (m *DiamlestResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamlestResponse.DiscardUnknown(m)
}

var xxx_messageInfo_DiamlestResponse proto.InternalMessageInfo

func (m *DiamlestResponse) GetNewlist() []*New {
	if m != nil {
		return m.Newlist
	}
	return nil
}

func (m *DiamlestResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *DiamlestResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Reward)(nil), "go.micro.srv.other.Reward")
	proto.RegisterType((*AchievementRequest)(nil), "go.micro.srv.other.AchievementRequest")
	proto.RegisterType((*AchievementResponse)(nil), "go.micro.srv.other.AchievementResponse")
	proto.RegisterType((*Box)(nil), "go.micro.srv.other.Box")
	proto.RegisterType((*TreasureMap)(nil), "go.micro.srv.other.TreasureMap")
	proto.RegisterType((*TreasureMapRequest)(nil), "go.micro.srv.other.TreasureMapRequest")
	proto.RegisterType((*TreasureMapResponse)(nil), "go.micro.srv.other.TreasureMapResponse")
	proto.RegisterType((*New)(nil), "go.micro.srv.other.new")
	proto.RegisterType((*PullNewRequest)(nil), "go.micro.srv.other.PullNewRequest")
	proto.RegisterType((*PullNewResponse)(nil), "go.micro.srv.other.PullNewResponse")
	proto.RegisterType((*LampRequest)(nil), "go.micro.srv.other.LampRequest")
	proto.RegisterType((*LampResponse)(nil), "go.micro.srv.other.LampResponse")
	proto.RegisterType((*LamplestRequest)(nil), "go.micro.srv.other.LamplestRequest")
	proto.RegisterType((*LamplestResponse)(nil), "go.micro.srv.other.LamplestResponse")
	proto.RegisterType((*StrengthRequest)(nil), "go.micro.srv.other.StrengthRequest")
	proto.RegisterType((*StrengthResponse)(nil), "go.micro.srv.other.StrengthResponse")
	proto.RegisterType((*StrelestRequest)(nil), "go.micro.srv.other.StrelestRequest")
	proto.RegisterType((*StrelestResponse)(nil), "go.micro.srv.other.StrelestResponse")
	proto.RegisterType((*DiamondRequest)(nil), "go.micro.srv.other.DiamondRequest")
	proto.RegisterType((*DiamondResponse)(nil), "go.micro.srv.other.DiamondResponse")
	proto.RegisterType((*DiamlestRequest)(nil), "go.micro.srv.other.DiamlestRequest")
	proto.RegisterType((*DiamlestResponse)(nil), "go.micro.srv.other.DiamlestResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 768 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x6f, 0x6b, 0xdb, 0x3e,
	0x10, 0xae, 0x9d, 0xd4, 0x69, 0xaf, 0x3f, 0x9a, 0xa2, 0xfe, 0xd8, 0x4c, 0x56, 0xb6, 0xa2, 0x96,
	0xad, 0xaf, 0x52, 0xd6, 0x0d, 0x46, 0xa1, 0xb0, 0x35, 0x2c, 0x8c, 0xb1, 0xae, 0x8c, 0xb4, 0xb0,
	0x57, 0x83, 0xaa, 0x89, 0x48, 0xcc, 0x62, 0x2b, 0x93, 0x95, 0x3f, 0xdd, 0xa7, 0xd8, 0xe7, 0xd8,
	0x8b, 0x7d, 0xb1, 0x7d, 0x89, 0x21, 0xdb, 0x92, 0x65, 0x57, 0x49, 0xa0, 0xd0, 0xbe, 0x8a, 0x2c,
	0xdd, 0x3d, 0xf7, 0xdc, 0x73, 0x77, 0x8a, 0xe0, 0xc9, 0x88, 0x33, 0xc1, 0x0e, 0xe9, 0x8c, 0x84,
	0xa3, 0x21, 0x55, 0xbf, 0xcd, 0x64, 0x17, 0xa1, 0x3e, 0x6b, 0x86, 0x41, 0x97, 0xb3, 0x66, 0xcc,
	0x27, 0x4d, 0x26, 0x06, 0x94, 0xe3, 0xd7, 0xe0, 0x75, 0xe8, 0x94, 0xf0, 0x1e, 0x42, 0x50, 0xed,
	0xb2, 0x1e, 0xf5, 0x9d, 0x5d, 0xe7, 0x60, 0xbd, 0x93, 0xac, 0xd1, 0x23, 0xf0, 0xa2, 0x71, 0x78,
	0x4d, 0xb9, 0xef, 0x26, 0xbb, 0xd9, 0x17, 0x3e, 0x01, 0x74, 0xda, 0x1d, 0x04, 0x74, 0x42, 0x43,
	0x1a, 0x89, 0x0e, 0xfd, 0x31, 0xa6, 0xb1, 0x90, 0x08, 0xf1, 0x77, 0x7a, 0xa3, 0x10, 0xe4, 0x5a,
	0xa3, 0xba, 0x39, 0x2a, 0xfe, 0xeb, 0xc0, 0x76, 0xc1, 0x3d, 0x1e, 0xb1, 0x28, 0xa6, 0xe8, 0x08,
	0x3c, 0x9e, 0x70, 0xf1, 0x9d, 0xdd, 0xca, 0xc1, 0xc6, 0x51, 0xa3, 0x79, 0x9b, 0x70, 0x33, 0x65,
	0xdb, 0xc9, 0x2c, 0xd1, 0x53, 0x80, 0x88, 0xce, 0xc4, 0xb9, 0xc9, 0xd2, 0xd8, 0x91, 0xf1, 0x23,
	0x12, 0x52, 0xbf, 0x92, 0xc6, 0x97, 0x6b, 0xe9, 0xd3, 0x65, 0x51, 0x2f, 0x10, 0x01, 0x8b, 0x4e,
	0xfd, 0x6a, 0xea, 0x93, 0xef, 0x14, 0xce, 0x5b, 0xfe, 0x6a, 0xe9, 0xbc, 0x85, 0xfe, 0x87, 0xd5,
	0x36, 0xe7, 0x11, 0xf3, 0xbd, 0xe4, 0x28, 0xfd, 0x90, 0x5a, 0xb5, 0x39, 0x0f, 0xe3, 0xbe, 0x5f,
	0x4b, 0xb5, 0x4a, 0xbf, 0x70, 0x1b, 0x2a, 0x2d, 0x36, 0x93, 0x44, 0xc4, 0xcd, 0x48, 0xcb, 0x2b,
	0xd7, 0xf3, 0xe4, 0xb5, 0x91, 0xc6, 0x3f, 0x61, 0xe3, 0x92, 0x53, 0x12, 0x8f, 0x39, 0xfd, 0x4c,
	0x46, 0x92, 0x43, 0x2c, 0x88, 0x50, 0x78, 0xe9, 0x87, 0x0e, 0xe2, 0x1a, 0x41, 0xb6, 0xa0, 0x32,
	0xe6, 0xc3, 0x0c, 0x4b, 0x2e, 0xd1, 0xa1, 0xd6, 0xb9, 0x9a, 0xe8, 0xfc, 0xd8, 0xa6, 0x73, 0x8b,
	0xcd, 0x94, 0xc8, 0xf8, 0x97, 0x03, 0xc8, 0x08, 0xbe, 0xa8, 0xde, 0x9b, 0xe0, 0x06, 0x93, 0x2c,
	0xbe, 0x1b, 0x4c, 0xa4, 0x4d, 0x8f, 0x08, 0xa2, 0x52, 0x91, 0x6b, 0xdd, 0x13, 0x55, 0xa3, 0xd3,
	0x76, 0x60, 0x3d, 0x1e, 0x10, 0x4e, 0x13, 0xc0, 0x54, 0xf2, 0x7c, 0x43, 0xe5, 0xe0, 0xe9, 0x1c,
	0xf0, 0x1f, 0x07, 0xb6, 0x0b, 0x94, 0xb2, 0x1e, 0x3a, 0x86, 0x5a, 0x48, 0x46, 0xc3, 0x20, 0x16,
	0x59, 0x13, 0x3d, 0xb3, 0x25, 0x67, 0x7a, 0x2a, 0x7b, 0xd4, 0x80, 0xb5, 0x3e, 0x1b, 0xf6, 0x44,
	0x10, 0x2a, 0x01, 0xf5, 0xb7, 0xb5, 0x8d, 0x74, 0x1b, 0x54, 0xed, 0x6d, 0xb0, 0x5a, 0x68, 0x83,
	0x8f, 0x50, 0x89, 0xe8, 0x54, 0x03, 0x39, 0x06, 0x50, 0x96, 0x9d, 0x9b, 0x57, 0x68, 0x07, 0xd6,
	0x3f, 0x50, 0x71, 0x21, 0x88, 0x18, 0xc7, 0x59, 0xcc, 0x7c, 0x03, 0xef, 0xc3, 0xe6, 0x97, 0xf1,
	0x70, 0x78, 0x4e, 0xa7, 0x0b, 0x2a, 0x81, 0x39, 0xd4, 0xb5, 0x55, 0x26, 0xce, 0x4b, 0xa8, 0x45,
	0x74, 0x6a, 0x88, 0x63, 0xad, 0x7c, 0x44, 0xa7, 0x1d, 0x65, 0x97, 0x27, 0xe9, 0xda, 0x93, 0xac,
	0x14, 0x92, 0xfc, 0x06, 0x1b, 0x67, 0x24, 0x5c, 0xd8, 0x20, 0x85, 0x42, 0xbb, 0xe5, 0x42, 0xab,
	0xd3, 0xa4, 0x08, 0x15, 0xe3, 0x54, 0x6e, 0xe0, 0x13, 0xf8, 0x2f, 0x85, 0xcf, 0xf2, 0xd1, 0xe4,
	0x1c, 0x3b, 0x39, 0xb7, 0x40, 0xee, 0x18, 0xea, 0x67, 0xc9, 0x75, 0x18, 0x2f, 0xbb, 0xb1, 0xca,
	0x33, 0x84, 0x63, 0xd8, 0xca, 0x5d, 0x1f, 0x4a, 0x4c, 0x02, 0xf5, 0x0b, 0xc1, 0x69, 0xd4, 0x17,
	0x83, 0xfb, 0x12, 0xf4, 0x1d, 0x6c, 0xe5, 0x21, 0xee, 0x24, 0xea, 0x9b, 0x94, 0xe4, 0x32, 0x51,
	0x6f, 0xb5, 0xb8, 0x94, 0x34, 0x77, 0x7c, 0x28, 0x49, 0xaf, 0x60, 0xf3, 0x7d, 0x40, 0x42, 0x16,
	0xf5, 0xee, 0x4b, 0xd1, 0xb7, 0x50, 0xd7, 0x11, 0xee, 0x2a, 0xa8, 0x04, 0xb8, 0x93, 0xa0, 0xb9,
	0xe3, 0x03, 0x09, 0x7a, 0xf4, 0xdb, 0x83, 0x5a, 0x3b, 0x7d, 0x64, 0xa0, 0x4b, 0xa8, 0x65, 0x17,
	0x0e, 0xc2, 0xb6, 0x30, 0xc5, 0x3b, 0xab, 0xb1, 0xb7, 0xd0, 0x26, 0x4d, 0x00, 0xaf, 0xa0, 0x4f,
	0x50, 0x95, 0xa3, 0x87, 0xac, 0xf7, 0xb8, 0x71, 0xd9, 0x34, 0x76, 0xe7, 0x1b, 0x68, 0xb0, 0xaf,
	0xb0, 0xa6, 0xe6, 0x18, 0xed, 0xcd, 0xb3, 0x37, 0xa4, 0x6f, 0xec, 0x2f, 0x36, 0x32, 0x81, 0xd5,
	0x20, 0xd9, 0x81, 0x4b, 0x93, 0x6c, 0x07, 0x2e, 0xcf, 0x62, 0x0e, 0x3c, 0x9f, 0x71, 0x69, 0xfa,
	0xe6, 0x03, 0x97, 0x18, 0x5f, 0x42, 0x2d, 0x6b, 0x54, 0x7b, 0xb5, 0x8a, 0x73, 0x62, 0xaf, 0x56,
	0xa9, 0xd3, 0x53, 0xba, 0xaa, 0x09, 0xd1, 0x5c, 0x97, 0xa5, 0x74, 0xcb, 0x7d, 0x8c, 0x57, 0xd0,
	0x55, 0xf1, 0xf9, 0xf3, 0x7c, 0xd9, 0xbf, 0x7a, 0x06, 0xff, 0x62, 0xa9, 0x9d, 0x19, 0xc1, 0x78,
	0x94, 0xda, 0x23, 0xdc, 0x7e, 0xf4, 0xda, 0x23, 0x58, 0x5e, 0xb7, 0x78, 0xe5, 0xda, 0x4b, 0x9e,
	0xe1, 0xaf, 0xfe, 0x05, 0x00, 0x00, 0xff, 0xff, 0x62, 0xf5, 0x3a, 0xef, 0xa5, 0x0b, 0x00, 0x00,
}
