// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_login

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

//login的参数
type LoginRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginRequest) Reset()         { *m = LoginRequest{} }
func (m *LoginRequest) String() string { return proto.CompactTextString(m) }
func (*LoginRequest) ProtoMessage()    {}
func (*LoginRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *LoginRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginRequest.Unmarshal(m, b)
}
func (m *LoginRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginRequest.Marshal(b, m, deterministic)
}
func (m *LoginRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginRequest.Merge(m, src)
}
func (m *LoginRequest) XXX_Size() int {
	return xxx_messageInfo_LoginRequest.Size(m)
}
func (m *LoginRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginRequest proto.InternalMessageInfo

func (m *LoginRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginResponse struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginResponse) Reset()         { *m = LoginResponse{} }
func (m *LoginResponse) String() string { return proto.CompactTextString(m) }
func (*LoginResponse) ProtoMessage()    {}
func (*LoginResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *LoginResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginResponse.Unmarshal(m, b)
}
func (m *LoginResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginResponse.Marshal(b, m, deterministic)
}
func (m *LoginResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginResponse.Merge(m, src)
}
func (m *LoginResponse) XXX_Size() int {
	return xxx_messageInfo_LoginResponse.Size(m)
}
func (m *LoginResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginResponse proto.InternalMessageInfo

func (m *LoginResponse) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *LoginResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *LoginResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//Config方法的参数
type ConfigRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigRequest) Reset()         { *m = ConfigRequest{} }
func (m *ConfigRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigRequest) ProtoMessage()    {}
func (*ConfigRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *ConfigRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigRequest.Unmarshal(m, b)
}
func (m *ConfigRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigRequest.Marshal(b, m, deterministic)
}
func (m *ConfigRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigRequest.Merge(m, src)
}
func (m *ConfigRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigRequest.Size(m)
}
func (m *ConfigRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigRequest proto.InternalMessageInfo

func (m *ConfigRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

type ConfigResponse struct {
	Datalist             []byte   `protobuf:"bytes,1,opt,name=datalist,proto3" json:"datalist,omitempty"`
	Configlist           *Config  `protobuf:"bytes,2,opt,name=configlist,proto3" json:"configlist,omitempty"`
	Errno                string   `protobuf:"bytes,3,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,4,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigResponse) Reset()         { *m = ConfigResponse{} }
func (m *ConfigResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigResponse) ProtoMessage()    {}
func (*ConfigResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *ConfigResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigResponse.Unmarshal(m, b)
}
func (m *ConfigResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigResponse.Marshal(b, m, deterministic)
}
func (m *ConfigResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigResponse.Merge(m, src)
}
func (m *ConfigResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigResponse.Size(m)
}
func (m *ConfigResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigResponse proto.InternalMessageInfo

func (m *ConfigResponse) GetDatalist() []byte {
	if m != nil {
		return m.Datalist
	}
	return nil
}

func (m *ConfigResponse) GetConfiglist() *Config {
	if m != nil {
		return m.Configlist
	}
	return nil
}

func (m *ConfigResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *ConfigResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//config数据格式
type Config struct {
	//场景属性表
	SceneDatalist []*SceneData `protobuf:"bytes,1,rep,name=SceneDatalist,proto3" json:"SceneDatalist,omitempty"`
	//各场景地块的开启金币数
	MassifDatalist []*MassifData `protobuf:"bytes,2,rep,name=MassifDatalist,proto3" json:"MassifDatalist,omitempty"`
	//农作物属性表
	Cropslist []*Crops `protobuf:"bytes,3,rep,name=cropslist,proto3" json:"cropslist,omitempty"`
	//全部收益数据
	AllProceedslist []*AllProceeds `protobuf:"bytes,4,rep,name=AllProceedslist,proto3" json:"AllProceedslist,omitempty"`
	//金币强化表
	GoldEnhancementDatalist []*GoldEnhancementData `protobuf:"bytes,5,rep,name=GoldEnhancementDatalist,proto3" json:"GoldEnhancementDatalist,omitempty"`
	//现金强化表
	MoneyEnhancementDatalist []*MoneyEnhancementData `protobuf:"bytes,6,rep,name=MoneyEnhancementDatalist,proto3" json:"MoneyEnhancementDatalist,omitempty"`
	//钻石强化表
	DiamondEnhancementDatalist []*DiamondEnhancementData `protobuf:"bytes,7,rep,name=DiamondEnhancementDatalist,proto3" json:"DiamondEnhancementDatalist,omitempty"`
	//植物碎片表
	PlantDebrislist []*PlantDebris `protobuf:"bytes,8,rep,name=PlantDebrislist,proto3" json:"PlantDebrislist,omitempty"`
	//邀请新人数值表
	NewPeoplelist []*NewPeople `protobuf:"bytes,9,rep,name=NewPeoplelist,proto3" json:"NewPeoplelist,omitempty"`
	//每日签到数值表
	SignInlist []*SignIn `protobuf:"bytes,10,rep,name=SignInlist,proto3" json:"SignInlist,omitempty"`
	//好友助理数值表
	FriendHelplist []*FriendHelp `protobuf:"bytes,11,rep,name=FriendHelplist,proto3" json:"FriendHelplist,omitempty"`
	//罐子可抽取数值表
	PotFragmentslist []*PotFragments `protobuf:"bytes,12,rep,name=PotFragmentslist,proto3" json:"PotFragmentslist,omitempty"`
	//道具表
	Proplist []*Prop `protobuf:"bytes,13,rep,name=Proplist,proto3" json:"Proplist,omitempty"`
	//随机道具表
	RandomProplist []*RandomProp `protobuf:"bytes,14,rep,name=RandomProplist,proto3" json:"RandomProplist,omitempty"`
	//抽奖数值表
	LuckDrawlist []*LuckDraw `protobuf:"bytes,15,rep,name=LuckDrawlist,proto3" json:"LuckDrawlist,omitempty"`
	//抽罐子价格表
	PotPricelist []*PotPrice `protobuf:"bytes,16,rep,name=PotPricelist,proto3" json:"PotPricelist,omitempty"`
	//成就数值表
	Achievementlist []*Achievement `protobuf:"bytes,17,rep,name=Achievementlist,proto3" json:"Achievementlist,omitempty"`
	//收割后产出倍数区间表
	Sectionlist []*Section `protobuf:"bytes,18,rep,name=Sectionlist,proto3" json:"Sectionlist,omitempty"`
	//金币自动生存
	AutoGoldlist []*AutoGold `protobuf:"bytes,19,rep,name=AutoGoldlist,proto3" json:"AutoGoldlist,omitempty"`
	//收割皮肤表
	Harvestlist []*HarvestSkin `protobuf:"bytes,20,rep,name=Harvestlist,proto3" json:"Harvestlist,omitempty"`
	//灯皮肤表
	Lamplist             []*Lamp  `protobuf:"bytes,21,rep,name=Lamplist,proto3" json:"Lamplist,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Config) Reset()         { *m = Config{} }
func (m *Config) String() string { return proto.CompactTextString(m) }
func (*Config) ProtoMessage()    {}
func (*Config) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *Config) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Config.Unmarshal(m, b)
}
func (m *Config) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Config.Marshal(b, m, deterministic)
}
func (m *Config) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Config.Merge(m, src)
}
func (m *Config) XXX_Size() int {
	return xxx_messageInfo_Config.Size(m)
}
func (m *Config) XXX_DiscardUnknown() {
	xxx_messageInfo_Config.DiscardUnknown(m)
}

var xxx_messageInfo_Config proto.InternalMessageInfo

func (m *Config) GetSceneDatalist() []*SceneData {
	if m != nil {
		return m.SceneDatalist
	}
	return nil
}

func (m *Config) GetMassifDatalist() []*MassifData {
	if m != nil {
		return m.MassifDatalist
	}
	return nil
}

func (m *Config) GetCropslist() []*Crops {
	if m != nil {
		return m.Cropslist
	}
	return nil
}

func (m *Config) GetAllProceedslist() []*AllProceeds {
	if m != nil {
		return m.AllProceedslist
	}
	return nil
}

func (m *Config) GetGoldEnhancementDatalist() []*GoldEnhancementData {
	if m != nil {
		return m.GoldEnhancementDatalist
	}
	return nil
}

func (m *Config) GetMoneyEnhancementDatalist() []*MoneyEnhancementData {
	if m != nil {
		return m.MoneyEnhancementDatalist
	}
	return nil
}

func (m *Config) GetDiamondEnhancementDatalist() []*DiamondEnhancementData {
	if m != nil {
		return m.DiamondEnhancementDatalist
	}
	return nil
}

func (m *Config) GetPlantDebrislist() []*PlantDebris {
	if m != nil {
		return m.PlantDebrislist
	}
	return nil
}

func (m *Config) GetNewPeoplelist() []*NewPeople {
	if m != nil {
		return m.NewPeoplelist
	}
	return nil
}

func (m *Config) GetSignInlist() []*SignIn {
	if m != nil {
		return m.SignInlist
	}
	return nil
}

func (m *Config) GetFriendHelplist() []*FriendHelp {
	if m != nil {
		return m.FriendHelplist
	}
	return nil
}

func (m *Config) GetPotFragmentslist() []*PotFragments {
	if m != nil {
		return m.PotFragmentslist
	}
	return nil
}

func (m *Config) GetProplist() []*Prop {
	if m != nil {
		return m.Proplist
	}
	return nil
}

func (m *Config) GetRandomProplist() []*RandomProp {
	if m != nil {
		return m.RandomProplist
	}
	return nil
}

func (m *Config) GetLuckDrawlist() []*LuckDraw {
	if m != nil {
		return m.LuckDrawlist
	}
	return nil
}

func (m *Config) GetPotPricelist() []*PotPrice {
	if m != nil {
		return m.PotPricelist
	}
	return nil
}

func (m *Config) GetAchievementlist() []*Achievement {
	if m != nil {
		return m.Achievementlist
	}
	return nil
}

func (m *Config) GetSectionlist() []*Section {
	if m != nil {
		return m.Sectionlist
	}
	return nil
}

func (m *Config) GetAutoGoldlist() []*AutoGold {
	if m != nil {
		return m.AutoGoldlist
	}
	return nil
}

func (m *Config) GetHarvestlist() []*HarvestSkin {
	if m != nil {
		return m.Harvestlist
	}
	return nil
}

func (m *Config) GetLamplist() []*Lamp {
	if m != nil {
		return m.Lamplist
	}
	return nil
}

//数据库数据格式
//场景属性表
type SceneData struct {
	ID                   string   `protobuf:"bytes,1,opt,name=ID,proto3" json:"ID,omitempty"`
	SceneCode            string   `protobuf:"bytes,2,opt,name=SceneCode,proto3" json:"SceneCode,omitempty"`
	Name                 string   `protobuf:"bytes,3,opt,name=Name,proto3" json:"Name,omitempty"`
	OutputAddition       string   `protobuf:"bytes,4,opt,name=OutputAddition,proto3" json:"OutputAddition,omitempty"`
	Permanent            string   `protobuf:"bytes,5,opt,name=Permanent,proto3" json:"Permanent,omitempty"`
	TimeLimit            string   `protobuf:"bytes,6,opt,name=TimeLimit,proto3" json:"TimeLimit,omitempty"`
	PriceDiamonds        string   `protobuf:"bytes,7,opt,name=PriceDiamonds,proto3" json:"PriceDiamonds,omitempty"`
	SmallUrl             string   `protobuf:"bytes,8,opt,name=SmallUrl,proto3" json:"SmallUrl,omitempty"`
	MaxUrl               string   `protobuf:"bytes,9,opt,name=MaxUrl,proto3" json:"MaxUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SceneData) Reset()         { *m = SceneData{} }
func (m *SceneData) String() string { return proto.CompactTextString(m) }
func (*SceneData) ProtoMessage()    {}
func (*SceneData) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *SceneData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SceneData.Unmarshal(m, b)
}
func (m *SceneData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SceneData.Marshal(b, m, deterministic)
}
func (m *SceneData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SceneData.Merge(m, src)
}
func (m *SceneData) XXX_Size() int {
	return xxx_messageInfo_SceneData.Size(m)
}
func (m *SceneData) XXX_DiscardUnknown() {
	xxx_messageInfo_SceneData.DiscardUnknown(m)
}

var xxx_messageInfo_SceneData proto.InternalMessageInfo

func (m *SceneData) GetID() string {
	if m != nil {
		return m.ID
	}
	return ""
}

func (m *SceneData) GetSceneCode() string {
	if m != nil {
		return m.SceneCode
	}
	return ""
}

func (m *SceneData) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *SceneData) GetOutputAddition() string {
	if m != nil {
		return m.OutputAddition
	}
	return ""
}

func (m *SceneData) GetPermanent() string {
	if m != nil {
		return m.Permanent
	}
	return ""
}

func (m *SceneData) GetTimeLimit() string {
	if m != nil {
		return m.TimeLimit
	}
	return ""
}

func (m *SceneData) GetPriceDiamonds() string {
	if m != nil {
		return m.PriceDiamonds
	}
	return ""
}

func (m *SceneData) GetSmallUrl() string {
	if m != nil {
		return m.SmallUrl
	}
	return ""
}

func (m *SceneData) GetMaxUrl() string {
	if m != nil {
		return m.MaxUrl
	}
	return ""
}

//各场景地块的开启金币数
type MassifData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SceneCode            string   `protobuf:"bytes,2,opt,name=SceneCode,proto3" json:"SceneCode,omitempty"`
	OnePrice             string   `protobuf:"bytes,3,opt,name=OnePrice,proto3" json:"OnePrice,omitempty"`
	TwoPrice             string   `protobuf:"bytes,4,opt,name=TwoPrice,proto3" json:"TwoPrice,omitempty"`
	ThreePrice           string   `protobuf:"bytes,5,opt,name=ThreePrice,proto3" json:"ThreePrice,omitempty"`
	FourPrice            string   `protobuf:"bytes,6,opt,name=FourPrice,proto3" json:"FourPrice,omitempty"`
	FivePrice            string   `protobuf:"bytes,7,opt,name=FivePrice,proto3" json:"FivePrice,omitempty"`
	SixPrice             string   `protobuf:"bytes,8,opt,name=SixPrice,proto3" json:"SixPrice,omitempty"`
	SevenPrice           string   `protobuf:"bytes,9,opt,name=SevenPrice,proto3" json:"SevenPrice,omitempty"`
	EightPrice           string   `protobuf:"bytes,10,opt,name=EightPrice,proto3" json:"EightPrice,omitempty"`
	NinePrice            string   `protobuf:"bytes,11,opt,name=NinePrice,proto3" json:"NinePrice,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MassifData) Reset()         { *m = MassifData{} }
func (m *MassifData) String() string { return proto.CompactTextString(m) }
func (*MassifData) ProtoMessage()    {}
func (*MassifData) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *MassifData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MassifData.Unmarshal(m, b)
}
func (m *MassifData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MassifData.Marshal(b, m, deterministic)
}
func (m *MassifData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MassifData.Merge(m, src)
}
func (m *MassifData) XXX_Size() int {
	return xxx_messageInfo_MassifData.Size(m)
}
func (m *MassifData) XXX_DiscardUnknown() {
	xxx_messageInfo_MassifData.DiscardUnknown(m)
}

var xxx_messageInfo_MassifData proto.InternalMessageInfo

func (m *MassifData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MassifData) GetSceneCode() string {
	if m != nil {
		return m.SceneCode
	}
	return ""
}

func (m *MassifData) GetOnePrice() string {
	if m != nil {
		return m.OnePrice
	}
	return ""
}

func (m *MassifData) GetTwoPrice() string {
	if m != nil {
		return m.TwoPrice
	}
	return ""
}

func (m *MassifData) GetThreePrice() string {
	if m != nil {
		return m.ThreePrice
	}
	return ""
}

func (m *MassifData) GetFourPrice() string {
	if m != nil {
		return m.FourPrice
	}
	return ""
}

func (m *MassifData) GetFivePrice() string {
	if m != nil {
		return m.FivePrice
	}
	return ""
}

func (m *MassifData) GetSixPrice() string {
	if m != nil {
		return m.SixPrice
	}
	return ""
}

func (m *MassifData) GetSevenPrice() string {
	if m != nil {
		return m.SevenPrice
	}
	return ""
}

func (m *MassifData) GetEightPrice() string {
	if m != nil {
		return m.EightPrice
	}
	return ""
}

func (m *MassifData) GetNinePrice() string {
	if m != nil {
		return m.NinePrice
	}
	return ""
}

//农作物属性表
type Crops struct {
	Id                            string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Name                          string   `protobuf:"bytes,2,opt,name=Name,proto3" json:"Name,omitempty"`
	CropCode                      string   `protobuf:"bytes,3,opt,name=CropCode,proto3" json:"CropCode,omitempty"`
	DefaultUnlock                 string   `protobuf:"bytes,4,opt,name=DefaultUnlock,proto3" json:"DefaultUnlock,omitempty"`
	Subordinate                   string   `protobuf:"bytes,5,opt,name=Subordinate,proto3" json:"Subordinate,omitempty"`
	CommonlyYield                 string   `protobuf:"bytes,6,opt,name=CommonlyYield,proto3" json:"CommonlyYield,omitempty"`
	GreenYield                    string   `protobuf:"bytes,7,opt,name=GreenYield,proto3" json:"GreenYield,omitempty"`
	BlueYield                     string   `protobuf:"bytes,8,opt,name=BlueYield,proto3" json:"BlueYield,omitempty"`
	VioletYield                   string   `protobuf:"bytes,9,opt,name=VioletYield,proto3" json:"VioletYield,omitempty"`
	OrangeYield                   string   `protobuf:"bytes,10,opt,name=OrangeYield,proto3" json:"OrangeYield,omitempty"`
	BasicProductionTime           string   `protobuf:"bytes,11,opt,name=BasicProductionTime,proto3" json:"BasicProductionTime,omitempty"`
	LimitProductionTime           string   `protobuf:"bytes,12,opt,name=LimitProductionTime,proto3" json:"LimitProductionTime,omitempty"`
	RegistrationRequiredPromotion string   `protobuf:"bytes,13,opt,name=RegistrationRequiredPromotion,proto3" json:"RegistrationRequiredPromotion,omitempty"`
	StageLiftingSpeed             string   `protobuf:"bytes,14,opt,name=StageLiftingSpeed,proto3" json:"StageLiftingSpeed,omitempty"`
	UpgradeBaseGold               string   `protobuf:"bytes,15,opt,name=UpgradeBaseGold,proto3" json:"UpgradeBaseGold,omitempty"`
	ExhibitionUrl                 string   `protobuf:"bytes,16,opt,name=ExhibitionUrl,proto3" json:"ExhibitionUrl,omitempty"`
	DynamicUrl                    string   `protobuf:"bytes,17,opt,name=DynamicUrl,proto3" json:"DynamicUrl,omitempty"`
	XXX_NoUnkeyedLiteral          struct{} `json:"-"`
	XXX_unrecognized              []byte   `json:"-"`
	XXX_sizecache                 int32    `json:"-"`
}

func (m *Crops) Reset()         { *m = Crops{} }
func (m *Crops) String() string { return proto.CompactTextString(m) }
func (*Crops) ProtoMessage()    {}
func (*Crops) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *Crops) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Crops.Unmarshal(m, b)
}
func (m *Crops) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Crops.Marshal(b, m, deterministic)
}
func (m *Crops) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Crops.Merge(m, src)
}
func (m *Crops) XXX_Size() int {
	return xxx_messageInfo_Crops.Size(m)
}
func (m *Crops) XXX_DiscardUnknown() {
	xxx_messageInfo_Crops.DiscardUnknown(m)
}

var xxx_messageInfo_Crops proto.InternalMessageInfo

func (m *Crops) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Crops) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *Crops) GetCropCode() string {
	if m != nil {
		return m.CropCode
	}
	return ""
}

func (m *Crops) GetDefaultUnlock() string {
	if m != nil {
		return m.DefaultUnlock
	}
	return ""
}

func (m *Crops) GetSubordinate() string {
	if m != nil {
		return m.Subordinate
	}
	return ""
}

func (m *Crops) GetCommonlyYield() string {
	if m != nil {
		return m.CommonlyYield
	}
	return ""
}

func (m *Crops) GetGreenYield() string {
	if m != nil {
		return m.GreenYield
	}
	return ""
}

func (m *Crops) GetBlueYield() string {
	if m != nil {
		return m.BlueYield
	}
	return ""
}

func (m *Crops) GetVioletYield() string {
	if m != nil {
		return m.VioletYield
	}
	return ""
}

func (m *Crops) GetOrangeYield() string {
	if m != nil {
		return m.OrangeYield
	}
	return ""
}

func (m *Crops) GetBasicProductionTime() string {
	if m != nil {
		return m.BasicProductionTime
	}
	return ""
}

func (m *Crops) GetLimitProductionTime() string {
	if m != nil {
		return m.LimitProductionTime
	}
	return ""
}

func (m *Crops) GetRegistrationRequiredPromotion() string {
	if m != nil {
		return m.RegistrationRequiredPromotion
	}
	return ""
}

func (m *Crops) GetStageLiftingSpeed() string {
	if m != nil {
		return m.StageLiftingSpeed
	}
	return ""
}

func (m *Crops) GetUpgradeBaseGold() string {
	if m != nil {
		return m.UpgradeBaseGold
	}
	return ""
}

func (m *Crops) GetExhibitionUrl() string {
	if m != nil {
		return m.ExhibitionUrl
	}
	return ""
}

func (m *Crops) GetDynamicUrl() string {
	if m != nil {
		return m.DynamicUrl
	}
	return ""
}

//全部收益数据
type AllProceeds struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=Code,proto3" json:"Code,omitempty"`
	ProceedsMultiple     string   `protobuf:"bytes,3,opt,name=ProceedsMultiple,proto3" json:"ProceedsMultiple,omitempty"`
	Consume              string   `protobuf:"bytes,4,opt,name=Consume,proto3" json:"Consume,omitempty"`
	ArtsUrl              string   `protobuf:"bytes,5,opt,name=ArtsUrl,proto3" json:"ArtsUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AllProceeds) Reset()         { *m = AllProceeds{} }
func (m *AllProceeds) String() string { return proto.CompactTextString(m) }
func (*AllProceeds) ProtoMessage()    {}
func (*AllProceeds) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *AllProceeds) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AllProceeds.Unmarshal(m, b)
}
func (m *AllProceeds) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AllProceeds.Marshal(b, m, deterministic)
}
func (m *AllProceeds) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AllProceeds.Merge(m, src)
}
func (m *AllProceeds) XXX_Size() int {
	return xxx_messageInfo_AllProceeds.Size(m)
}
func (m *AllProceeds) XXX_DiscardUnknown() {
	xxx_messageInfo_AllProceeds.DiscardUnknown(m)
}

var xxx_messageInfo_AllProceeds proto.InternalMessageInfo

func (m *AllProceeds) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AllProceeds) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

func (m *AllProceeds) GetProceedsMultiple() string {
	if m != nil {
		return m.ProceedsMultiple
	}
	return ""
}

func (m *AllProceeds) GetConsume() string {
	if m != nil {
		return m.Consume
	}
	return ""
}

func (m *AllProceeds) GetArtsUrl() string {
	if m != nil {
		return m.ArtsUrl
	}
	return ""
}

//金币强化表
type GoldEnhancementData struct {
	Id                             string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	MassifCode                     string   `protobuf:"bytes,2,opt,name=MassifCode,proto3" json:"MassifCode,omitempty"`
	Level                          string   `protobuf:"bytes,3,opt,name=Level,proto3" json:"Level,omitempty"`
	EarningsMultiplier             string   `protobuf:"bytes,4,opt,name=EarningsMultiplier,proto3" json:"EarningsMultiplier,omitempty"`
	IntensiveConsumption           string   `protobuf:"bytes,5,opt,name=IntensiveConsumption,proto3" json:"IntensiveConsumption,omitempty"`
	AutomatedProductionConsumption string   `protobuf:"bytes,6,opt,name=AutomatedProductionConsumption,proto3" json:"AutomatedProductionConsumption,omitempty"`
	ArtsUrl                        string   `protobuf:"bytes,7,opt,name=ArtsUrl,proto3" json:"ArtsUrl,omitempty"`
	XXX_NoUnkeyedLiteral           struct{} `json:"-"`
	XXX_unrecognized               []byte   `json:"-"`
	XXX_sizecache                  int32    `json:"-"`
}

func (m *GoldEnhancementData) Reset()         { *m = GoldEnhancementData{} }
func (m *GoldEnhancementData) String() string { return proto.CompactTextString(m) }
func (*GoldEnhancementData) ProtoMessage()    {}
func (*GoldEnhancementData) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *GoldEnhancementData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoldEnhancementData.Unmarshal(m, b)
}
func (m *GoldEnhancementData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoldEnhancementData.Marshal(b, m, deterministic)
}
func (m *GoldEnhancementData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoldEnhancementData.Merge(m, src)
}
func (m *GoldEnhancementData) XXX_Size() int {
	return xxx_messageInfo_GoldEnhancementData.Size(m)
}
func (m *GoldEnhancementData) XXX_DiscardUnknown() {
	xxx_messageInfo_GoldEnhancementData.DiscardUnknown(m)
}

var xxx_messageInfo_GoldEnhancementData proto.InternalMessageInfo

func (m *GoldEnhancementData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *GoldEnhancementData) GetMassifCode() string {
	if m != nil {
		return m.MassifCode
	}
	return ""
}

func (m *GoldEnhancementData) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *GoldEnhancementData) GetEarningsMultiplier() string {
	if m != nil {
		return m.EarningsMultiplier
	}
	return ""
}

func (m *GoldEnhancementData) GetIntensiveConsumption() string {
	if m != nil {
		return m.IntensiveConsumption
	}
	return ""
}

func (m *GoldEnhancementData) GetAutomatedProductionConsumption() string {
	if m != nil {
		return m.AutomatedProductionConsumption
	}
	return ""
}

func (m *GoldEnhancementData) GetArtsUrl() string {
	if m != nil {
		return m.ArtsUrl
	}
	return ""
}

//现金强化表
type MoneyEnhancementData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Level                string   `protobuf:"bytes,2,opt,name=Level,proto3" json:"Level,omitempty"`
	EarningsMultiplier   string   `protobuf:"bytes,3,opt,name=EarningsMultiplier,proto3" json:"EarningsMultiplier,omitempty"`
	IntensiveConsumption string   `protobuf:"bytes,4,opt,name=IntensiveConsumption,proto3" json:"IntensiveConsumption,omitempty"`
	ArtsUrl              string   `protobuf:"bytes,5,opt,name=ArtsUrl,proto3" json:"ArtsUrl,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *MoneyEnhancementData) Reset()         { *m = MoneyEnhancementData{} }
func (m *MoneyEnhancementData) String() string { return proto.CompactTextString(m) }
func (*MoneyEnhancementData) ProtoMessage()    {}
func (*MoneyEnhancementData) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *MoneyEnhancementData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_MoneyEnhancementData.Unmarshal(m, b)
}
func (m *MoneyEnhancementData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_MoneyEnhancementData.Marshal(b, m, deterministic)
}
func (m *MoneyEnhancementData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_MoneyEnhancementData.Merge(m, src)
}
func (m *MoneyEnhancementData) XXX_Size() int {
	return xxx_messageInfo_MoneyEnhancementData.Size(m)
}
func (m *MoneyEnhancementData) XXX_DiscardUnknown() {
	xxx_messageInfo_MoneyEnhancementData.DiscardUnknown(m)
}

var xxx_messageInfo_MoneyEnhancementData proto.InternalMessageInfo

func (m *MoneyEnhancementData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *MoneyEnhancementData) GetLevel() string {
	if m != nil {
		return m.Level
	}
	return ""
}

func (m *MoneyEnhancementData) GetEarningsMultiplier() string {
	if m != nil {
		return m.EarningsMultiplier
	}
	return ""
}

func (m *MoneyEnhancementData) GetIntensiveConsumption() string {
	if m != nil {
		return m.IntensiveConsumption
	}
	return ""
}

func (m *MoneyEnhancementData) GetArtsUrl() string {
	if m != nil {
		return m.ArtsUrl
	}
	return ""
}

//钻石强化表
type DiamondEnhancementData struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	EarningsMultiplier   string   `protobuf:"bytes,2,opt,name=EarningsMultiplier,proto3" json:"EarningsMultiplier,omitempty"`
	ImmediateRevenue     string   `protobuf:"bytes,3,opt,name=ImmediateRevenue,proto3" json:"ImmediateRevenue,omitempty"`
	IntensiveConsumption string   `protobuf:"bytes,4,opt,name=IntensiveConsumption,proto3" json:"IntensiveConsumption,omitempty"`
	ArtsUrl              string   `protobuf:"bytes,5,opt,name=ArtsUrl,proto3" json:"ArtsUrl,omitempty"`
	AttributeClass       string   `protobuf:"bytes,6,opt,name=AttributeClass,proto3" json:"AttributeClass,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *DiamondEnhancementData) Reset()         { *m = DiamondEnhancementData{} }
func (m *DiamondEnhancementData) String() string { return proto.CompactTextString(m) }
func (*DiamondEnhancementData) ProtoMessage()    {}
func (*DiamondEnhancementData) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{11}
}

func (m *DiamondEnhancementData) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_DiamondEnhancementData.Unmarshal(m, b)
}
func (m *DiamondEnhancementData) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_DiamondEnhancementData.Marshal(b, m, deterministic)
}
func (m *DiamondEnhancementData) XXX_Merge(src proto.Message) {
	xxx_messageInfo_DiamondEnhancementData.Merge(m, src)
}
func (m *DiamondEnhancementData) XXX_Size() int {
	return xxx_messageInfo_DiamondEnhancementData.Size(m)
}
func (m *DiamondEnhancementData) XXX_DiscardUnknown() {
	xxx_messageInfo_DiamondEnhancementData.DiscardUnknown(m)
}

var xxx_messageInfo_DiamondEnhancementData proto.InternalMessageInfo

func (m *DiamondEnhancementData) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *DiamondEnhancementData) GetEarningsMultiplier() string {
	if m != nil {
		return m.EarningsMultiplier
	}
	return ""
}

func (m *DiamondEnhancementData) GetImmediateRevenue() string {
	if m != nil {
		return m.ImmediateRevenue
	}
	return ""
}

func (m *DiamondEnhancementData) GetIntensiveConsumption() string {
	if m != nil {
		return m.IntensiveConsumption
	}
	return ""
}

func (m *DiamondEnhancementData) GetArtsUrl() string {
	if m != nil {
		return m.ArtsUrl
	}
	return ""
}

func (m *DiamondEnhancementData) GetAttributeClass() string {
	if m != nil {
		return m.AttributeClass
	}
	return ""
}

//植物碎片表
type PlantDebris struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PlantName            string   `protobuf:"bytes,2,opt,name=PlantName,proto3" json:"PlantName,omitempty"`
	PlantCode            string   `protobuf:"bytes,3,opt,name=PlantCode,proto3" json:"PlantCode,omitempty"`
	PlantLevel           string   `protobuf:"bytes,4,opt,name=PlantLevel,proto3" json:"PlantLevel,omitempty"`
	FragmentCode         string   `protobuf:"bytes,5,opt,name=FragmentCode,proto3" json:"FragmentCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PlantDebris) Reset()         { *m = PlantDebris{} }
func (m *PlantDebris) String() string { return proto.CompactTextString(m) }
func (*PlantDebris) ProtoMessage()    {}
func (*PlantDebris) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{12}
}

func (m *PlantDebris) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PlantDebris.Unmarshal(m, b)
}
func (m *PlantDebris) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PlantDebris.Marshal(b, m, deterministic)
}
func (m *PlantDebris) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PlantDebris.Merge(m, src)
}
func (m *PlantDebris) XXX_Size() int {
	return xxx_messageInfo_PlantDebris.Size(m)
}
func (m *PlantDebris) XXX_DiscardUnknown() {
	xxx_messageInfo_PlantDebris.DiscardUnknown(m)
}

var xxx_messageInfo_PlantDebris proto.InternalMessageInfo

func (m *PlantDebris) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PlantDebris) GetPlantName() string {
	if m != nil {
		return m.PlantName
	}
	return ""
}

func (m *PlantDebris) GetPlantCode() string {
	if m != nil {
		return m.PlantCode
	}
	return ""
}

func (m *PlantDebris) GetPlantLevel() string {
	if m != nil {
		return m.PlantLevel
	}
	return ""
}

func (m *PlantDebris) GetFragmentCode() string {
	if m != nil {
		return m.FragmentCode
	}
	return ""
}

//邀请新人数值表
type NewPeople struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Number               string   `protobuf:"bytes,2,opt,name=Number,proto3" json:"Number,omitempty"`
	RewardCode           string   `protobuf:"bytes,3,opt,name=RewardCode,proto3" json:"RewardCode,omitempty"`
	RewardNumber         string   `protobuf:"bytes,4,opt,name=RewardNumber,proto3" json:"RewardNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *NewPeople) Reset()         { *m = NewPeople{} }
func (m *NewPeople) String() string { return proto.CompactTextString(m) }
func (*NewPeople) ProtoMessage()    {}
func (*NewPeople) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{13}
}

func (m *NewPeople) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_NewPeople.Unmarshal(m, b)
}
func (m *NewPeople) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_NewPeople.Marshal(b, m, deterministic)
}
func (m *NewPeople) XXX_Merge(src proto.Message) {
	xxx_messageInfo_NewPeople.Merge(m, src)
}
func (m *NewPeople) XXX_Size() int {
	return xxx_messageInfo_NewPeople.Size(m)
}
func (m *NewPeople) XXX_DiscardUnknown() {
	xxx_messageInfo_NewPeople.DiscardUnknown(m)
}

var xxx_messageInfo_NewPeople proto.InternalMessageInfo

func (m *NewPeople) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *NewPeople) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

func (m *NewPeople) GetRewardCode() string {
	if m != nil {
		return m.RewardCode
	}
	return ""
}

func (m *NewPeople) GetRewardNumber() string {
	if m != nil {
		return m.RewardNumber
	}
	return ""
}

//每日签到数值表
type SignIn struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	Days                 string   `protobuf:"bytes,2,opt,name=Days,proto3" json:"Days,omitempty"`
	RewardCode           string   `protobuf:"bytes,3,opt,name=RewardCode,proto3" json:"RewardCode,omitempty"`
	RewardNumber         string   `protobuf:"bytes,4,opt,name=RewardNumber,proto3" json:"RewardNumber,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SignIn) Reset()         { *m = SignIn{} }
func (m *SignIn) String() string { return proto.CompactTextString(m) }
func (*SignIn) ProtoMessage()    {}
func (*SignIn) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{14}
}

func (m *SignIn) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SignIn.Unmarshal(m, b)
}
func (m *SignIn) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SignIn.Marshal(b, m, deterministic)
}
func (m *SignIn) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SignIn.Merge(m, src)
}
func (m *SignIn) XXX_Size() int {
	return xxx_messageInfo_SignIn.Size(m)
}
func (m *SignIn) XXX_DiscardUnknown() {
	xxx_messageInfo_SignIn.DiscardUnknown(m)
}

var xxx_messageInfo_SignIn proto.InternalMessageInfo

func (m *SignIn) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *SignIn) GetDays() string {
	if m != nil {
		return m.Days
	}
	return ""
}

func (m *SignIn) GetRewardCode() string {
	if m != nil {
		return m.RewardCode
	}
	return ""
}

func (m *SignIn) GetRewardNumber() string {
	if m != nil {
		return m.RewardNumber
	}
	return ""
}

//好友助理数值表
type FriendHelp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PeopleNumber         string   `protobuf:"bytes,2,opt,name=PeopleNumber,proto3" json:"PeopleNumber,omitempty"`
	Reward1Code          string   `protobuf:"bytes,3,opt,name=Reward1Code,proto3" json:"Reward1Code,omitempty"`
	Reward1Number        string   `protobuf:"bytes,4,opt,name=Reward1Number,proto3" json:"Reward1Number,omitempty"`
	Reward2Code          string   `protobuf:"bytes,5,opt,name=Reward2Code,proto3" json:"Reward2Code,omitempty"`
	Reward2Number        string   `protobuf:"bytes,6,opt,name=Reward2Number,proto3" json:"Reward2Number,omitempty"`
	Reward3Code          string   `protobuf:"bytes,7,opt,name=Reward3Code,proto3" json:"Reward3Code,omitempty"`
	Reward3Number        string   `protobuf:"bytes,8,opt,name=Reward3Number,proto3" json:"Reward3Number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *FriendHelp) Reset()         { *m = FriendHelp{} }
func (m *FriendHelp) String() string { return proto.CompactTextString(m) }
func (*FriendHelp) ProtoMessage()    {}
func (*FriendHelp) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{15}
}

func (m *FriendHelp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_FriendHelp.Unmarshal(m, b)
}
func (m *FriendHelp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_FriendHelp.Marshal(b, m, deterministic)
}
func (m *FriendHelp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_FriendHelp.Merge(m, src)
}
func (m *FriendHelp) XXX_Size() int {
	return xxx_messageInfo_FriendHelp.Size(m)
}
func (m *FriendHelp) XXX_DiscardUnknown() {
	xxx_messageInfo_FriendHelp.DiscardUnknown(m)
}

var xxx_messageInfo_FriendHelp proto.InternalMessageInfo

func (m *FriendHelp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *FriendHelp) GetPeopleNumber() string {
	if m != nil {
		return m.PeopleNumber
	}
	return ""
}

func (m *FriendHelp) GetReward1Code() string {
	if m != nil {
		return m.Reward1Code
	}
	return ""
}

func (m *FriendHelp) GetReward1Number() string {
	if m != nil {
		return m.Reward1Number
	}
	return ""
}

func (m *FriendHelp) GetReward2Code() string {
	if m != nil {
		return m.Reward2Code
	}
	return ""
}

func (m *FriendHelp) GetReward2Number() string {
	if m != nil {
		return m.Reward2Number
	}
	return ""
}

func (m *FriendHelp) GetReward3Code() string {
	if m != nil {
		return m.Reward3Code
	}
	return ""
}

func (m *FriendHelp) GetReward3Number() string {
	if m != nil {
		return m.Reward3Number
	}
	return ""
}

//罐子可抽取数值表
type PotFragments struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PlantName            string   `protobuf:"bytes,2,opt,name=PlantName,proto3" json:"PlantName,omitempty"`
	PlantCode            string   `protobuf:"bytes,3,opt,name=PlantCode,proto3" json:"PlantCode,omitempty"`
	PlantLevel           string   `protobuf:"bytes,4,opt,name=PlantLevel,proto3" json:"PlantLevel,omitempty"`
	FragmentCode         string   `protobuf:"bytes,5,opt,name=FragmentCode,proto3" json:"FragmentCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PotFragments) Reset()         { *m = PotFragments{} }
func (m *PotFragments) String() string { return proto.CompactTextString(m) }
func (*PotFragments) ProtoMessage()    {}
func (*PotFragments) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{16}
}

func (m *PotFragments) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotFragments.Unmarshal(m, b)
}
func (m *PotFragments) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotFragments.Marshal(b, m, deterministic)
}
func (m *PotFragments) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotFragments.Merge(m, src)
}
func (m *PotFragments) XXX_Size() int {
	return xxx_messageInfo_PotFragments.Size(m)
}
func (m *PotFragments) XXX_DiscardUnknown() {
	xxx_messageInfo_PotFragments.DiscardUnknown(m)
}

var xxx_messageInfo_PotFragments proto.InternalMessageInfo

func (m *PotFragments) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PotFragments) GetPlantName() string {
	if m != nil {
		return m.PlantName
	}
	return ""
}

func (m *PotFragments) GetPlantCode() string {
	if m != nil {
		return m.PlantCode
	}
	return ""
}

func (m *PotFragments) GetPlantLevel() string {
	if m != nil {
		return m.PlantLevel
	}
	return ""
}

func (m *PotFragments) GetFragmentCode() string {
	if m != nil {
		return m.FragmentCode
	}
	return ""
}

//道具表
type Prop struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PropCode             string   `protobuf:"bytes,2,opt,name=PropCode,proto3" json:"PropCode,omitempty"`
	PropName             string   `protobuf:"bytes,3,opt,name=PropName,proto3" json:"PropName,omitempty"`
	Introduce            string   `protobuf:"bytes,4,opt,name=Introduce,proto3" json:"Introduce,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Prop) Reset()         { *m = Prop{} }
func (m *Prop) String() string { return proto.CompactTextString(m) }
func (*Prop) ProtoMessage()    {}
func (*Prop) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{17}
}

func (m *Prop) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Prop.Unmarshal(m, b)
}
func (m *Prop) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Prop.Marshal(b, m, deterministic)
}
func (m *Prop) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Prop.Merge(m, src)
}
func (m *Prop) XXX_Size() int {
	return xxx_messageInfo_Prop.Size(m)
}
func (m *Prop) XXX_DiscardUnknown() {
	xxx_messageInfo_Prop.DiscardUnknown(m)
}

var xxx_messageInfo_Prop proto.InternalMessageInfo

func (m *Prop) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Prop) GetPropCode() string {
	if m != nil {
		return m.PropCode
	}
	return ""
}

func (m *Prop) GetPropName() string {
	if m != nil {
		return m.PropName
	}
	return ""
}

func (m *Prop) GetIntroduce() string {
	if m != nil {
		return m.Introduce
	}
	return ""
}

//随机道具表
type RandomProp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PropCode             string   `protobuf:"bytes,2,opt,name=PropCode,proto3" json:"PropCode,omitempty"`
	PropName             string   `protobuf:"bytes,3,opt,name=PropName,proto3" json:"PropName,omitempty"`
	Reward1              string   `protobuf:"bytes,4,opt,name=Reward1,proto3" json:"Reward1,omitempty"`
	Reward1Max           string   `protobuf:"bytes,5,opt,name=Reward1Max,proto3" json:"Reward1Max,omitempty"`
	Reward1Small         string   `protobuf:"bytes,6,opt,name=Reward1Small,proto3" json:"Reward1Small,omitempty"`
	Reward2              string   `protobuf:"bytes,7,opt,name=Reward2,proto3" json:"Reward2,omitempty"`
	Reward2Max           string   `protobuf:"bytes,8,opt,name=Reward2Max,proto3" json:"Reward2Max,omitempty"`
	Reward2Small         string   `protobuf:"bytes,9,opt,name=Reward2Small,proto3" json:"Reward2Small,omitempty"`
	Reward3              string   `protobuf:"bytes,10,opt,name=Reward3,proto3" json:"Reward3,omitempty"`
	OutputTime           string   `protobuf:"bytes,11,opt,name=OutputTime,proto3" json:"OutputTime,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RandomProp) Reset()         { *m = RandomProp{} }
func (m *RandomProp) String() string { return proto.CompactTextString(m) }
func (*RandomProp) ProtoMessage()    {}
func (*RandomProp) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{18}
}

func (m *RandomProp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RandomProp.Unmarshal(m, b)
}
func (m *RandomProp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RandomProp.Marshal(b, m, deterministic)
}
func (m *RandomProp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RandomProp.Merge(m, src)
}
func (m *RandomProp) XXX_Size() int {
	return xxx_messageInfo_RandomProp.Size(m)
}
func (m *RandomProp) XXX_DiscardUnknown() {
	xxx_messageInfo_RandomProp.DiscardUnknown(m)
}

var xxx_messageInfo_RandomProp proto.InternalMessageInfo

func (m *RandomProp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *RandomProp) GetPropCode() string {
	if m != nil {
		return m.PropCode
	}
	return ""
}

func (m *RandomProp) GetPropName() string {
	if m != nil {
		return m.PropName
	}
	return ""
}

func (m *RandomProp) GetReward1() string {
	if m != nil {
		return m.Reward1
	}
	return ""
}

func (m *RandomProp) GetReward1Max() string {
	if m != nil {
		return m.Reward1Max
	}
	return ""
}

func (m *RandomProp) GetReward1Small() string {
	if m != nil {
		return m.Reward1Small
	}
	return ""
}

func (m *RandomProp) GetReward2() string {
	if m != nil {
		return m.Reward2
	}
	return ""
}

func (m *RandomProp) GetReward2Max() string {
	if m != nil {
		return m.Reward2Max
	}
	return ""
}

func (m *RandomProp) GetReward2Small() string {
	if m != nil {
		return m.Reward2Small
	}
	return ""
}

func (m *RandomProp) GetReward3() string {
	if m != nil {
		return m.Reward3
	}
	return ""
}

func (m *RandomProp) GetOutputTime() string {
	if m != nil {
		return m.OutputTime
	}
	return ""
}

//抽奖数值表
type LuckDraw struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PlantCode            string   `protobuf:"bytes,2,opt,name=PlantCode,proto3" json:"PlantCode,omitempty"`
	PlantNumber          string   `protobuf:"bytes,3,opt,name=PlantNumber,proto3" json:"PlantNumber,omitempty"`
	Probability          string   `protobuf:"bytes,4,opt,name=Probability,proto3" json:"Probability,omitempty"`
	PropName             string   `protobuf:"bytes,5,opt,name=PropName,proto3" json:"PropName,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LuckDraw) Reset()         { *m = LuckDraw{} }
func (m *LuckDraw) String() string { return proto.CompactTextString(m) }
func (*LuckDraw) ProtoMessage()    {}
func (*LuckDraw) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{19}
}

func (m *LuckDraw) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LuckDraw.Unmarshal(m, b)
}
func (m *LuckDraw) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LuckDraw.Marshal(b, m, deterministic)
}
func (m *LuckDraw) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LuckDraw.Merge(m, src)
}
func (m *LuckDraw) XXX_Size() int {
	return xxx_messageInfo_LuckDraw.Size(m)
}
func (m *LuckDraw) XXX_DiscardUnknown() {
	xxx_messageInfo_LuckDraw.DiscardUnknown(m)
}

var xxx_messageInfo_LuckDraw proto.InternalMessageInfo

func (m *LuckDraw) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *LuckDraw) GetPlantCode() string {
	if m != nil {
		return m.PlantCode
	}
	return ""
}

func (m *LuckDraw) GetPlantNumber() string {
	if m != nil {
		return m.PlantNumber
	}
	return ""
}

func (m *LuckDraw) GetProbability() string {
	if m != nil {
		return m.Probability
	}
	return ""
}

func (m *LuckDraw) GetPropName() string {
	if m != nil {
		return m.PropName
	}
	return ""
}

//抽罐子价格表
type PotPrice struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	PotCode              string   `protobuf:"bytes,2,opt,name=PotCode,proto3" json:"PotCode,omitempty"`
	PotName              string   `protobuf:"bytes,3,opt,name=PotName,proto3" json:"PotName,omitempty"`
	CurrencyCode         string   `protobuf:"bytes,4,opt,name=CurrencyCode,proto3" json:"CurrencyCode,omitempty"`
	CurrencyNumbe        string   `protobuf:"bytes,5,opt,name=CurrencyNumbe,proto3" json:"CurrencyNumbe,omitempty"`
	FreeTime             string   `protobuf:"bytes,6,opt,name=FreeTime,proto3" json:"FreeTime,omitempty"`
	LuckDrawCode         string   `protobuf:"bytes,7,opt,name=LuckDrawCode,proto3" json:"LuckDrawCode,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PotPrice) Reset()         { *m = PotPrice{} }
func (m *PotPrice) String() string { return proto.CompactTextString(m) }
func (*PotPrice) ProtoMessage()    {}
func (*PotPrice) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{20}
}

func (m *PotPrice) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PotPrice.Unmarshal(m, b)
}
func (m *PotPrice) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PotPrice.Marshal(b, m, deterministic)
}
func (m *PotPrice) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PotPrice.Merge(m, src)
}
func (m *PotPrice) XXX_Size() int {
	return xxx_messageInfo_PotPrice.Size(m)
}
func (m *PotPrice) XXX_DiscardUnknown() {
	xxx_messageInfo_PotPrice.DiscardUnknown(m)
}

var xxx_messageInfo_PotPrice proto.InternalMessageInfo

func (m *PotPrice) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *PotPrice) GetPotCode() string {
	if m != nil {
		return m.PotCode
	}
	return ""
}

func (m *PotPrice) GetPotName() string {
	if m != nil {
		return m.PotName
	}
	return ""
}

func (m *PotPrice) GetCurrencyCode() string {
	if m != nil {
		return m.CurrencyCode
	}
	return ""
}

func (m *PotPrice) GetCurrencyNumbe() string {
	if m != nil {
		return m.CurrencyNumbe
	}
	return ""
}

func (m *PotPrice) GetFreeTime() string {
	if m != nil {
		return m.FreeTime
	}
	return ""
}

func (m *PotPrice) GetLuckDrawCode() string {
	if m != nil {
		return m.LuckDrawCode
	}
	return ""
}

//成就数值表
type Achievement struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	UserLevel            string   `protobuf:"bytes,2,opt,name=UserLevel,proto3" json:"UserLevel,omitempty"`
	TitleCode            string   `protobuf:"bytes,3,opt,name=TitleCode,proto3" json:"TitleCode,omitempty"`
	TitlName             string   `protobuf:"bytes,4,opt,name=TitlName,proto3" json:"TitlName,omitempty"`
	CumulativeDiam       string   `protobuf:"bytes,5,opt,name=CumulativeDiam,proto3" json:"CumulativeDiam,omitempty"`
	CumulativeGold       string   `protobuf:"bytes,6,opt,name=CumulativeGold,proto3" json:"CumulativeGold,omitempty"`
	CumulativeMone       string   `protobuf:"bytes,7,opt,name=CumulativeMone,proto3" json:"CumulativeMone,omitempty"`
	HarvestTimes         string   `protobuf:"bytes,8,opt,name=HarvestTimes,proto3" json:"HarvestTimes,omitempty"`
	Reward1Code          string   `protobuf:"bytes,9,opt,name=Reward1Code,proto3" json:"Reward1Code,omitempty"`
	Reward1Number        string   `protobuf:"bytes,10,opt,name=Reward1Number,proto3" json:"Reward1Number,omitempty"`
	Reward2Code          string   `protobuf:"bytes,11,opt,name=Reward2Code,proto3" json:"Reward2Code,omitempty"`
	Reward2Number        string   `protobuf:"bytes,12,opt,name=Reward2Number,proto3" json:"Reward2Number,omitempty"`
	Reward3Code          string   `protobuf:"bytes,13,opt,name=Reward3Code,proto3" json:"Reward3Code,omitempty"`
	Reward3Number        string   `protobuf:"bytes,14,opt,name=Reward3Number,proto3" json:"Reward3Number,omitempty"`
	Url                  string   `protobuf:"bytes,15,opt,name=Url,proto3" json:"Url,omitempty"`
	Promote              string   `protobuf:"bytes,16,opt,name=Promote,proto3" json:"Promote,omitempty"`
	D1                   string   `protobuf:"bytes,17,opt,name=D1,proto3" json:"D1,omitempty"`
	D2                   string   `protobuf:"bytes,18,opt,name=D2,proto3" json:"D2,omitempty"`
	D3                   string   `protobuf:"bytes,19,opt,name=D3,proto3" json:"D3,omitempty"`
	D4                   string   `protobuf:"bytes,20,opt,name=D4,proto3" json:"D4,omitempty"`
	D5                   string   `protobuf:"bytes,21,opt,name=D5,proto3" json:"D5,omitempty"`
	D6                   string   `protobuf:"bytes,22,opt,name=D6,proto3" json:"D6,omitempty"`
	D7                   string   `protobuf:"bytes,23,opt,name=D7,proto3" json:"D7,omitempty"`
	D8                   string   `protobuf:"bytes,24,opt,name=D8,proto3" json:"D8,omitempty"`
	D9                   string   `protobuf:"bytes,25,opt,name=D9,proto3" json:"D9,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Achievement) Reset()         { *m = Achievement{} }
func (m *Achievement) String() string { return proto.CompactTextString(m) }
func (*Achievement) ProtoMessage()    {}
func (*Achievement) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{21}
}

func (m *Achievement) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Achievement.Unmarshal(m, b)
}
func (m *Achievement) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Achievement.Marshal(b, m, deterministic)
}
func (m *Achievement) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Achievement.Merge(m, src)
}
func (m *Achievement) XXX_Size() int {
	return xxx_messageInfo_Achievement.Size(m)
}
func (m *Achievement) XXX_DiscardUnknown() {
	xxx_messageInfo_Achievement.DiscardUnknown(m)
}

var xxx_messageInfo_Achievement proto.InternalMessageInfo

func (m *Achievement) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Achievement) GetUserLevel() string {
	if m != nil {
		return m.UserLevel
	}
	return ""
}

func (m *Achievement) GetTitleCode() string {
	if m != nil {
		return m.TitleCode
	}
	return ""
}

func (m *Achievement) GetTitlName() string {
	if m != nil {
		return m.TitlName
	}
	return ""
}

func (m *Achievement) GetCumulativeDiam() string {
	if m != nil {
		return m.CumulativeDiam
	}
	return ""
}

func (m *Achievement) GetCumulativeGold() string {
	if m != nil {
		return m.CumulativeGold
	}
	return ""
}

func (m *Achievement) GetCumulativeMone() string {
	if m != nil {
		return m.CumulativeMone
	}
	return ""
}

func (m *Achievement) GetHarvestTimes() string {
	if m != nil {
		return m.HarvestTimes
	}
	return ""
}

func (m *Achievement) GetReward1Code() string {
	if m != nil {
		return m.Reward1Code
	}
	return ""
}

func (m *Achievement) GetReward1Number() string {
	if m != nil {
		return m.Reward1Number
	}
	return ""
}

func (m *Achievement) GetReward2Code() string {
	if m != nil {
		return m.Reward2Code
	}
	return ""
}

func (m *Achievement) GetReward2Number() string {
	if m != nil {
		return m.Reward2Number
	}
	return ""
}

func (m *Achievement) GetReward3Code() string {
	if m != nil {
		return m.Reward3Code
	}
	return ""
}

func (m *Achievement) GetReward3Number() string {
	if m != nil {
		return m.Reward3Number
	}
	return ""
}

func (m *Achievement) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *Achievement) GetPromote() string {
	if m != nil {
		return m.Promote
	}
	return ""
}

func (m *Achievement) GetD1() string {
	if m != nil {
		return m.D1
	}
	return ""
}

func (m *Achievement) GetD2() string {
	if m != nil {
		return m.D2
	}
	return ""
}

func (m *Achievement) GetD3() string {
	if m != nil {
		return m.D3
	}
	return ""
}

func (m *Achievement) GetD4() string {
	if m != nil {
		return m.D4
	}
	return ""
}

func (m *Achievement) GetD5() string {
	if m != nil {
		return m.D5
	}
	return ""
}

func (m *Achievement) GetD6() string {
	if m != nil {
		return m.D6
	}
	return ""
}

func (m *Achievement) GetD7() string {
	if m != nil {
		return m.D7
	}
	return ""
}

func (m *Achievement) GetD8() string {
	if m != nil {
		return m.D8
	}
	return ""
}

func (m *Achievement) GetD9() string {
	if m != nil {
		return m.D9
	}
	return ""
}

//收割后产出倍数区间表
type Section struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SmallGold            string   `protobuf:"bytes,2,opt,name=SmallGold,proto3" json:"SmallGold,omitempty"`
	MaxGold              string   `protobuf:"bytes,3,opt,name=MaxGold,proto3" json:"MaxGold,omitempty"`
	Multiple             string   `protobuf:"bytes,4,opt,name=Multiple,proto3" json:"Multiple,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Section) Reset()         { *m = Section{} }
func (m *Section) String() string { return proto.CompactTextString(m) }
func (*Section) ProtoMessage()    {}
func (*Section) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{22}
}

func (m *Section) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Section.Unmarshal(m, b)
}
func (m *Section) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Section.Marshal(b, m, deterministic)
}
func (m *Section) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Section.Merge(m, src)
}
func (m *Section) XXX_Size() int {
	return xxx_messageInfo_Section.Size(m)
}
func (m *Section) XXX_DiscardUnknown() {
	xxx_messageInfo_Section.DiscardUnknown(m)
}

var xxx_messageInfo_Section proto.InternalMessageInfo

func (m *Section) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Section) GetSmallGold() string {
	if m != nil {
		return m.SmallGold
	}
	return ""
}

func (m *Section) GetMaxGold() string {
	if m != nil {
		return m.MaxGold
	}
	return ""
}

func (m *Section) GetMultiple() string {
	if m != nil {
		return m.Multiple
	}
	return ""
}

//金币自动生存
type AutoGold struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	SceneCode            string   `protobuf:"bytes,2,opt,name=SceneCode,proto3" json:"SceneCode,omitempty"`
	Auto                 string   `protobuf:"bytes,3,opt,name=Auto,proto3" json:"Auto,omitempty"`
	AutoConsume          string   `protobuf:"bytes,4,opt,name=AutoConsume,proto3" json:"AutoConsume,omitempty"`
	Url                  string   `protobuf:"bytes,5,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *AutoGold) Reset()         { *m = AutoGold{} }
func (m *AutoGold) String() string { return proto.CompactTextString(m) }
func (*AutoGold) ProtoMessage()    {}
func (*AutoGold) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{23}
}

func (m *AutoGold) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_AutoGold.Unmarshal(m, b)
}
func (m *AutoGold) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_AutoGold.Marshal(b, m, deterministic)
}
func (m *AutoGold) XXX_Merge(src proto.Message) {
	xxx_messageInfo_AutoGold.Merge(m, src)
}
func (m *AutoGold) XXX_Size() int {
	return xxx_messageInfo_AutoGold.Size(m)
}
func (m *AutoGold) XXX_DiscardUnknown() {
	xxx_messageInfo_AutoGold.DiscardUnknown(m)
}

var xxx_messageInfo_AutoGold proto.InternalMessageInfo

func (m *AutoGold) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *AutoGold) GetSceneCode() string {
	if m != nil {
		return m.SceneCode
	}
	return ""
}

func (m *AutoGold) GetAuto() string {
	if m != nil {
		return m.Auto
	}
	return ""
}

func (m *AutoGold) GetAutoConsume() string {
	if m != nil {
		return m.AutoConsume
	}
	return ""
}

func (m *AutoGold) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

//收割皮肤表
type HarvestSkin struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	CarSkin              string   `protobuf:"bytes,2,opt,name=CarSkin,proto3" json:"CarSkin,omitempty"`
	CarName              string   `protobuf:"bytes,3,opt,name=CarName,proto3" json:"CarName,omitempty"`
	CarProduce           string   `protobuf:"bytes,4,opt,name=CarProduce,proto3" json:"CarProduce,omitempty"`
	Permanent            string   `protobuf:"bytes,5,opt,name=Permanent,proto3" json:"Permanent,omitempty"`
	CarTime              string   `protobuf:"bytes,6,opt,name=CarTime,proto3" json:"CarTime,omitempty"`
	Price                string   `protobuf:"bytes,7,opt,name=Price,proto3" json:"Price,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *HarvestSkin) Reset()         { *m = HarvestSkin{} }
func (m *HarvestSkin) String() string { return proto.CompactTextString(m) }
func (*HarvestSkin) ProtoMessage()    {}
func (*HarvestSkin) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{24}
}

func (m *HarvestSkin) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_HarvestSkin.Unmarshal(m, b)
}
func (m *HarvestSkin) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_HarvestSkin.Marshal(b, m, deterministic)
}
func (m *HarvestSkin) XXX_Merge(src proto.Message) {
	xxx_messageInfo_HarvestSkin.Merge(m, src)
}
func (m *HarvestSkin) XXX_Size() int {
	return xxx_messageInfo_HarvestSkin.Size(m)
}
func (m *HarvestSkin) XXX_DiscardUnknown() {
	xxx_messageInfo_HarvestSkin.DiscardUnknown(m)
}

var xxx_messageInfo_HarvestSkin proto.InternalMessageInfo

func (m *HarvestSkin) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *HarvestSkin) GetCarSkin() string {
	if m != nil {
		return m.CarSkin
	}
	return ""
}

func (m *HarvestSkin) GetCarName() string {
	if m != nil {
		return m.CarName
	}
	return ""
}

func (m *HarvestSkin) GetCarProduce() string {
	if m != nil {
		return m.CarProduce
	}
	return ""
}

func (m *HarvestSkin) GetPermanent() string {
	if m != nil {
		return m.Permanent
	}
	return ""
}

func (m *HarvestSkin) GetCarTime() string {
	if m != nil {
		return m.CarTime
	}
	return ""
}

func (m *HarvestSkin) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *HarvestSkin) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

//灯皮肤表
type Lamp struct {
	Id                   string   `protobuf:"bytes,1,opt,name=Id,proto3" json:"Id,omitempty"`
	LampSkin             string   `protobuf:"bytes,2,opt,name=LampSkin,proto3" json:"LampSkin,omitempty"`
	LampName             string   `protobuf:"bytes,3,opt,name=LampName,proto3" json:"LampName,omitempty"`
	LampAddition         string   `protobuf:"bytes,4,opt,name=LampAddition,proto3" json:"LampAddition,omitempty"`
	Permanent            string   `protobuf:"bytes,5,opt,name=Permanent,proto3" json:"Permanent,omitempty"`
	LampTime             string   `protobuf:"bytes,6,opt,name=LampTime,proto3" json:"LampTime,omitempty"`
	Price                string   `protobuf:"bytes,7,opt,name=Price,proto3" json:"Price,omitempty"`
	Url                  string   `protobuf:"bytes,8,opt,name=Url,proto3" json:"Url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lamp) Reset()         { *m = Lamp{} }
func (m *Lamp) String() string { return proto.CompactTextString(m) }
func (*Lamp) ProtoMessage()    {}
func (*Lamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{25}
}

func (m *Lamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lamp.Unmarshal(m, b)
}
func (m *Lamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lamp.Marshal(b, m, deterministic)
}
func (m *Lamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lamp.Merge(m, src)
}
func (m *Lamp) XXX_Size() int {
	return xxx_messageInfo_Lamp.Size(m)
}
func (m *Lamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Lamp.DiscardUnknown(m)
}

var xxx_messageInfo_Lamp proto.InternalMessageInfo

func (m *Lamp) GetId() string {
	if m != nil {
		return m.Id
	}
	return ""
}

func (m *Lamp) GetLampSkin() string {
	if m != nil {
		return m.LampSkin
	}
	return ""
}

func (m *Lamp) GetLampName() string {
	if m != nil {
		return m.LampName
	}
	return ""
}

func (m *Lamp) GetLampAddition() string {
	if m != nil {
		return m.LampAddition
	}
	return ""
}

func (m *Lamp) GetPermanent() string {
	if m != nil {
		return m.Permanent
	}
	return ""
}

func (m *Lamp) GetLampTime() string {
	if m != nil {
		return m.LampTime
	}
	return ""
}

func (m *Lamp) GetPrice() string {
	if m != nil {
		return m.Price
	}
	return ""
}

func (m *Lamp) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func init() {
	proto.RegisterType((*LoginRequest)(nil), "go.micro.srv.login.LoginRequest")
	proto.RegisterType((*LoginResponse)(nil), "go.micro.srv.login.LoginResponse")
	proto.RegisterType((*ConfigRequest)(nil), "go.micro.srv.login.ConfigRequest")
	proto.RegisterType((*ConfigResponse)(nil), "go.micro.srv.login.ConfigResponse")
	proto.RegisterType((*Config)(nil), "go.micro.srv.login.config")
	proto.RegisterType((*SceneData)(nil), "go.micro.srv.login.SceneData")
	proto.RegisterType((*MassifData)(nil), "go.micro.srv.login.MassifData")
	proto.RegisterType((*Crops)(nil), "go.micro.srv.login.crops")
	proto.RegisterType((*AllProceeds)(nil), "go.micro.srv.login.AllProceeds")
	proto.RegisterType((*GoldEnhancementData)(nil), "go.micro.srv.login.GoldEnhancementData")
	proto.RegisterType((*MoneyEnhancementData)(nil), "go.micro.srv.login.MoneyEnhancementData")
	proto.RegisterType((*DiamondEnhancementData)(nil), "go.micro.srv.login.DiamondEnhancementData")
	proto.RegisterType((*PlantDebris)(nil), "go.micro.srv.login.PlantDebris")
	proto.RegisterType((*NewPeople)(nil), "go.micro.srv.login.NewPeople")
	proto.RegisterType((*SignIn)(nil), "go.micro.srv.login.SignIn")
	proto.RegisterType((*FriendHelp)(nil), "go.micro.srv.login.FriendHelp")
	proto.RegisterType((*PotFragments)(nil), "go.micro.srv.login.PotFragments")
	proto.RegisterType((*Prop)(nil), "go.micro.srv.login.Prop")
	proto.RegisterType((*RandomProp)(nil), "go.micro.srv.login.RandomProp")
	proto.RegisterType((*LuckDraw)(nil), "go.micro.srv.login.LuckDraw")
	proto.RegisterType((*PotPrice)(nil), "go.micro.srv.login.PotPrice")
	proto.RegisterType((*Achievement)(nil), "go.micro.srv.login.Achievement")
	proto.RegisterType((*Section)(nil), "go.micro.srv.login.Section")
	proto.RegisterType((*AutoGold)(nil), "go.micro.srv.login.AutoGold")
	proto.RegisterType((*HarvestSkin)(nil), "go.micro.srv.login.HarvestSkin")
	proto.RegisterType((*Lamp)(nil), "go.micro.srv.login.Lamp")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 2149 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xcc, 0x59, 0x4b, 0x6f, 0x1b, 0xc9,
	0x11, 0x0e, 0xa9, 0x07, 0xa9, 0xa2, 0x24, 0xcb, 0x6d, 0xaf, 0x77, 0x56, 0xbb, 0xeb, 0x38, 0x93,
	0x20, 0x31, 0x8c, 0x40, 0x89, 0x29, 0xef, 0x7a, 0x37, 0x40, 0x80, 0xc8, 0xa4, 0xb4, 0x2b, 0x40,
	0xb2, 0xb9, 0x43, 0x3b, 0x40, 0x8e, 0x2d, 0xb2, 0x4d, 0x75, 0x34, 0x0f, 0x6e, 0xcf, 0x50, 0x8f,
	0x5b, 0xee, 0x39, 0xe5, 0x12, 0xec, 0x25, 0x01, 0x72, 0xc8, 0x2d, 0xbf, 0x20, 0xbf, 0x20, 0xc8,
	0x2d, 0x40, 0x0e, 0xf9, 0x27, 0x01, 0x72, 0x49, 0x50, 0xd5, 0xdd, 0x33, 0x3d, 0xc3, 0xa1, 0xa4,
	0x05, 0x7c, 0xc8, 0x89, 0x53, 0x5f, 0x3d, 0xba, 0xba, 0xba, 0xba, 0xba, 0xab, 0x09, 0x1f, 0x4e,
	0x55, 0x92, 0x25, 0x3f, 0x11, 0x97, 0x3c, 0x9a, 0x86, 0xc2, 0xfe, 0xee, 0x10, 0xca, 0xd8, 0x24,
	0xd9, 0x89, 0xe4, 0x48, 0x25, 0x3b, 0xa9, 0x3a, 0xdf, 0x09, 0x93, 0x89, 0x8c, 0x7d, 0x1f, 0xd6,
	0x8f, 0xf0, 0x23, 0x10, 0x5f, 0xcf, 0x44, 0x9a, 0x31, 0x06, 0xcb, 0x63, 0x9e, 0x71, 0xaf, 0xf1,
	0xa8, 0xf1, 0x78, 0x3d, 0xa0, 0x6f, 0xff, 0x2b, 0xd8, 0x30, 0x32, 0xe9, 0x34, 0x89, 0x53, 0x81,
	0x42, 0xe9, 0x99, 0xb8, 0x22, 0xa1, 0xb5, 0x80, 0xbe, 0xd9, 0x7d, 0x58, 0xd9, 0x57, 0x2a, 0x4e,
	0xbc, 0x26, 0x81, 0x9a, 0x60, 0x0f, 0x60, 0x75, 0x5f, 0xa9, 0x28, 0x9d, 0x78, 0x4b, 0x04, 0x1b,
	0xca, 0xff, 0x3e, 0x6c, 0xf4, 0x92, 0xf8, 0xad, 0x9c, 0x38, 0xe3, 0x56, 0x4d, 0xfa, 0xbf, 0x6f,
	0xc0, 0xa6, 0x95, 0x32, 0x23, 0x6f, 0x43, 0x1b, 0x5d, 0x0a, 0x65, 0x9a, 0x19, 0x17, 0x73, 0x9a,
	0xfd, 0x0c, 0x60, 0x44, 0xd2, 0xc4, 0x45, 0x37, 0x3a, 0xdd, 0xed, 0x9d, 0xf9, 0x39, 0xef, 0x68,
	0xa9, 0xc0, 0x91, 0x2e, 0xbc, 0x5f, 0xaa, 0xf7, 0x7e, 0xb9, 0xe4, 0xfd, 0xbf, 0x3b, 0xb0, 0xaa,
	0x95, 0x59, 0x0f, 0x36, 0x86, 0x23, 0x11, 0x8b, 0x7e, 0xe1, 0xd5, 0xd2, 0xe3, 0x4e, 0xf7, 0xe3,
	0xba, 0x71, 0x73, 0xc1, 0xa0, 0xac, 0xc3, 0x0e, 0x60, 0xf3, 0x98, 0xa7, 0xa9, 0x7c, 0x9b, 0x5b,
	0x69, 0x92, 0x95, 0x87, 0x75, 0x56, 0x0a, 0xc9, 0xa0, 0xa2, 0xc5, 0x9e, 0xc3, 0xda, 0x48, 0x25,
	0xd3, 0x94, 0x4c, 0x2c, 0x91, 0x89, 0x0f, 0x6a, 0x03, 0x80, 0x42, 0x41, 0x21, 0xcb, 0x0e, 0xe1,
	0xce, 0x5e, 0x18, 0x0e, 0x54, 0x32, 0x12, 0x62, 0xac, 0xd5, 0x97, 0x49, 0xfd, 0xbb, 0x75, 0xea,
	0x8e, 0x68, 0x50, 0xd5, 0x63, 0x1c, 0xde, 0xff, 0x22, 0x09, 0xc7, 0xfb, 0xf1, 0x29, 0x8f, 0x47,
	0x22, 0x12, 0x71, 0x96, 0x4f, 0x6a, 0x85, 0x4c, 0xfe, 0xa8, 0xce, 0x64, 0x8d, 0x4a, 0xb0, 0xc8,
	0x0e, 0x1b, 0x83, 0x77, 0x9c, 0xc4, 0xe2, 0xaa, 0x6e, 0x8c, 0x55, 0x1a, 0xe3, 0x71, 0x6d, 0xe0,
	0x6a, 0x74, 0x82, 0x85, 0x96, 0xd8, 0xaf, 0x61, 0xbb, 0x2f, 0x79, 0x94, 0xc4, 0xb5, 0x73, 0x69,
	0xd1, 0x38, 0x4f, 0xea, 0xc6, 0xa9, 0xd7, 0x0a, 0xae, 0xb1, 0x86, 0xf1, 0x1f, 0x84, 0x3c, 0xce,
	0xfa, 0xe2, 0x44, 0x49, 0x1d, 0xff, 0xf6, 0xe2, 0xf8, 0x3b, 0xa2, 0x41, 0x55, 0x0f, 0x13, 0xf2,
	0xa5, 0xb8, 0x18, 0x88, 0x64, 0x1a, 0x0a, 0x32, 0xb4, 0xb6, 0x38, 0x21, 0x73, 0xc1, 0xa0, 0xac,
	0x83, 0x5b, 0x69, 0x28, 0x27, 0xf1, 0x61, 0x4c, 0x16, 0x80, 0x2c, 0xd4, 0x6e, 0x25, 0x2d, 0x15,
	0x38, 0xd2, 0x98, 0xcc, 0x07, 0x4a, 0x8a, 0x78, 0xfc, 0xa5, 0x08, 0xa7, 0xa4, 0xdf, 0x59, 0x9c,
	0xcc, 0x85, 0x64, 0x50, 0xd1, 0x62, 0x47, 0xb0, 0x35, 0x48, 0xb2, 0x03, 0xc5, 0x27, 0x18, 0x2a,
	0x1d, 0x94, 0x75, 0xb2, 0xf4, 0xa8, 0x36, 0x28, 0x8e, 0x6c, 0x30, 0xa7, 0xc9, 0x9e, 0x41, 0x7b,
	0xa0, 0x12, 0xed, 0xcf, 0x06, 0x59, 0xf1, 0x6a, 0xad, 0xa8, 0x64, 0x1a, 0xe4, 0x92, 0x38, 0x97,
	0x80, 0xc7, 0xe3, 0x24, 0xca, 0x75, 0x37, 0x17, 0xcf, 0xa5, 0x90, 0x0c, 0x2a, 0x5a, 0xec, 0x17,
	0xb0, 0x7e, 0x34, 0x1b, 0x9d, 0xf5, 0x15, 0xbf, 0x20, 0x2b, 0x77, 0xc8, 0xca, 0x47, 0x75, 0x56,
	0xac, 0x5c, 0x50, 0xd2, 0x40, 0x0b, 0x83, 0x24, 0x1b, 0x28, 0x39, 0xd2, 0xab, 0xba, 0xb5, 0xd8,
	0x82, 0x95, 0x0b, 0x4a, 0x1a, 0xb4, 0xc7, 0x47, 0xa7, 0x52, 0x9c, 0x53, 0xea, 0x91, 0x91, 0xbb,
	0xd7, 0xec, 0xf1, 0x42, 0x34, 0xa8, 0xea, 0xb1, 0x9f, 0x43, 0x67, 0x28, 0x46, 0x99, 0x4c, 0x74,
	0x7e, 0x30, 0x32, 0xf3, 0x61, 0x6d, 0x7e, 0x68, 0xb1, 0xc0, 0x95, 0xc7, 0xb9, 0xec, 0xcd, 0xb2,
	0x04, 0xb7, 0x37, 0xe9, 0xdf, 0x5b, 0x3c, 0x17, 0x2b, 0x17, 0x94, 0x34, 0xd8, 0x1e, 0x74, 0xbe,
	0xe4, 0xea, 0x5c, 0xa4, 0x7a, 0x1e, 0xf7, 0x17, 0xcf, 0xc3, 0x88, 0x0d, 0xcf, 0x64, 0x1c, 0xb8,
	0x3a, 0x98, 0x10, 0x47, 0x78, 0x38, 0xa2, 0xfe, 0x7b, 0x8b, 0x13, 0x02, 0x65, 0x82, 0x5c, 0xd2,
	0xff, 0x6d, 0x13, 0xd6, 0xf2, 0xda, 0xcd, 0x36, 0xa1, 0x79, 0xd8, 0x37, 0x47, 0x56, 0xf3, 0xb0,
	0xcf, 0x3e, 0x32, 0xcc, 0x5e, 0x32, 0x16, 0xe6, 0x1c, 0x2c, 0x00, 0x3c, 0xe2, 0x5e, 0xf2, 0x48,
	0x98, 0x23, 0x86, 0xbe, 0xd9, 0x0f, 0x61, 0xf3, 0xd5, 0x2c, 0x9b, 0xce, 0xb2, 0xbd, 0xf1, 0x58,
	0x62, 0x80, 0xcc, 0x49, 0x53, 0x41, 0xd1, 0xf2, 0x40, 0xa8, 0x88, 0xc7, 0x22, 0xc6, 0x3a, 0x4a,
	0x96, 0x73, 0x00, 0xb9, 0xaf, 0x65, 0x24, 0x8e, 0x64, 0x24, 0xb1, 0x02, 0x12, 0x37, 0x07, 0xd8,
	0x0f, 0x60, 0x83, 0xb2, 0xc0, 0xd4, 0x9f, 0xd4, 0x6b, 0x91, 0x44, 0x19, 0xc4, 0x93, 0x75, 0x18,
	0xf1, 0x30, 0x7c, 0xa3, 0x42, 0xaf, 0x4d, 0x02, 0x39, 0x8d, 0xe7, 0xe0, 0x31, 0xbf, 0x44, 0xce,
	0x9a, 0x3e, 0x07, 0x35, 0xe5, 0xff, 0xad, 0x09, 0x50, 0x1c, 0x41, 0x14, 0x8e, 0x71, 0x1e, 0x8e,
	0xf1, 0x0d, 0xe1, 0xd8, 0x86, 0xf6, 0xab, 0x58, 0x90, 0x13, 0x26, 0x24, 0x39, 0x8d, 0xbc, 0xd7,
	0x17, 0x89, 0xe6, 0xe9, 0x80, 0xe4, 0x34, 0x7b, 0x08, 0xf0, 0xfa, 0x54, 0x09, 0xa3, 0xa9, 0x63,
	0xe1, 0x20, 0x38, 0xea, 0x41, 0x32, 0x53, 0x9a, 0x6d, 0x82, 0x91, 0x03, 0xc4, 0x95, 0xe7, 0x46,
	0xb9, 0x65, 0xb8, 0x16, 0xa0, 0x20, 0xc8, 0x4b, 0xcd, 0xb4, 0x41, 0x30, 0x34, 0x8e, 0x3b, 0x14,
	0xe7, 0x22, 0xd6, 0x5c, 0x1d, 0x08, 0x07, 0x41, 0xfe, 0xbe, 0x9c, 0x9c, 0xea, 0x1d, 0xe7, 0x81,
	0xe6, 0x17, 0x08, 0x8e, 0xfc, 0x52, 0xda, 0x09, 0x77, 0xf4, 0xc8, 0x39, 0xe0, 0xff, 0x77, 0x19,
	0x56, 0xe8, 0x3c, 0x9e, 0x8b, 0xa2, 0x4d, 0x9b, 0xa6, 0x93, 0x36, 0xdb, 0xd0, 0xee, 0xa9, 0x64,
	0x4a, 0x81, 0x35, 0xb1, 0xb3, 0x34, 0x2e, 0x77, 0x5f, 0xbc, 0xe5, 0xb3, 0x30, 0x7b, 0x13, 0x87,
	0xc9, 0xe8, 0xcc, 0x04, 0xb0, 0x0c, 0xb2, 0x47, 0xd0, 0x19, 0xce, 0x4e, 0x12, 0x35, 0x96, 0x31,
	0xcf, 0x6c, 0x18, 0x5d, 0x08, 0xed, 0xf4, 0x92, 0x28, 0x4a, 0xe2, 0xf0, 0xea, 0x57, 0x52, 0x84,
	0x63, 0x13, 0xcb, 0x32, 0x88, 0xb3, 0xfe, 0x42, 0x09, 0x11, 0x6b, 0x11, 0x1d, 0x50, 0x07, 0xc1,
	0x59, 0xbf, 0x08, 0x67, 0x42, 0xb3, 0x75, 0x48, 0x0b, 0x00, 0xbd, 0xf8, 0xa5, 0x4c, 0x42, 0x91,
	0x69, 0xbe, 0x0e, 0xaa, 0x0b, 0xa1, 0xc4, 0x2b, 0xc5, 0xe3, 0x89, 0xb1, 0xa0, 0xc3, 0xea, 0x42,
	0xec, 0xa7, 0x70, 0xef, 0x05, 0x4f, 0xe5, 0x68, 0xa0, 0x92, 0xf1, 0x8c, 0x8a, 0x0c, 0xa6, 0xbe,
	0x89, 0x70, 0x1d, 0x0b, 0x35, 0x68, 0x67, 0x54, 0x34, 0xd6, 0xb5, 0x46, 0x0d, 0x8b, 0xf5, 0xe1,
	0xe3, 0x40, 0x4c, 0x64, 0x9a, 0x29, 0x4e, 0xe5, 0x4c, 0x7c, 0x3d, 0x93, 0x4a, 0x8c, 0x07, 0x2a,
	0x89, 0x12, 0xda, 0xb5, 0x1b, 0xa4, 0x7b, 0xbd, 0x10, 0xfb, 0x31, 0xdc, 0x1d, 0x66, 0x7c, 0x22,
	0x8e, 0xe4, 0xdb, 0x4c, 0xc6, 0x93, 0xe1, 0x54, 0x88, 0xb1, 0xb7, 0x49, 0x9a, 0xf3, 0x0c, 0xf6,
	0x18, 0xee, 0xbc, 0x99, 0x4e, 0x14, 0x1f, 0x8b, 0x17, 0x3c, 0x15, 0x58, 0xfa, 0xbc, 0x3b, 0x24,
	0x5b, 0x85, 0x71, 0xa5, 0xf6, 0x2f, 0x4f, 0xe5, 0x09, 0x95, 0x0a, 0xdc, 0xa5, 0x5b, 0x7a, 0xa5,
	0x4a, 0x20, 0xae, 0x54, 0xff, 0x2a, 0xe6, 0x91, 0x1c, 0xa1, 0xc8, 0x5d, 0xbd, 0x52, 0x05, 0xe2,
	0xff, 0xae, 0x01, 0x1d, 0xe7, 0x32, 0x57, 0x97, 0x87, 0xce, 0x46, 0xa6, 0x6f, 0xf6, 0x04, 0xb6,
	0xac, 0xfc, 0xf1, 0x2c, 0xcc, 0xe4, 0x34, 0xb4, 0xf9, 0x38, 0x87, 0x33, 0x0f, 0x5a, 0xbd, 0x24,
	0x4e, 0x67, 0x91, 0xdd, 0xd2, 0x96, 0x44, 0xce, 0x9e, 0xca, 0x52, 0x74, 0x4b, 0xe7, 0xa1, 0x25,
	0xfd, 0x3f, 0x35, 0xe1, 0x5e, 0xcd, 0x2d, 0x70, 0xce, 0xb7, 0x87, 0xb6, 0x0e, 0x39, 0x1e, 0x3a,
	0x08, 0x5e, 0xef, 0x8f, 0xc4, 0xb9, 0x08, 0xed, 0xf5, 0x9e, 0x08, 0xb6, 0x03, 0x6c, 0x9f, 0xab,
	0x58, 0xc6, 0x13, 0xeb, 0xa5, 0x14, 0xca, 0x38, 0x57, 0xc3, 0x61, 0x5d, 0xb8, 0x7f, 0x18, 0x67,
	0x22, 0x4e, 0xe5, 0xb9, 0xd0, 0xbe, 0x4f, 0x69, 0xf1, 0xb5, 0xd3, 0xb5, 0x3c, 0x76, 0x00, 0x0f,
	0xf1, 0xe4, 0x8a, 0x78, 0x46, 0x99, 0x60, 0x92, 0xca, 0xd5, 0xd6, 0xdb, 0xea, 0x06, 0x29, 0x37,
	0x46, 0xad, 0x72, 0x8c, 0xfe, 0xda, 0x80, 0xfb, 0x75, 0x97, 0xd8, 0xb9, 0x20, 0xe5, 0x41, 0x68,
	0xde, 0x1c, 0x84, 0xa5, 0x6f, 0x1d, 0x84, 0xe5, 0x6b, 0x82, 0xb0, 0x78, 0x81, 0xff, 0xd3, 0x80,
	0x07, 0xf5, 0xf7, 0xe2, 0x39, 0xf7, 0xeb, 0x1d, 0x6d, 0x2e, 0x74, 0xf4, 0x09, 0x6c, 0x1d, 0x46,
	0x91, 0x18, 0x4b, 0x9e, 0x89, 0x00, 0xcb, 0xf4, 0x2c, 0xcf, 0xcd, 0x2a, 0xfe, 0x6e, 0x27, 0x85,
	0x87, 0xfa, 0x5e, 0x96, 0x29, 0x79, 0x32, 0xcb, 0x44, 0x2f, 0xe4, 0x69, 0x6a, 0xd6, 0xb8, 0x82,
	0xfa, 0x7f, 0x68, 0x40, 0xc7, 0xb9, 0xbe, 0xd7, 0x9d, 0x9f, 0xc4, 0x76, 0xca, 0x7f, 0x01, 0xe4,
	0x5c, 0xe7, 0x10, 0x28, 0x00, 0xdc, 0x11, 0x44, 0xe8, 0x15, 0xd7, 0xf3, 0x70, 0x10, 0xe6, 0xc3,
	0xba, 0xbd, 0x20, 0x93, 0x01, 0x3d, 0x85, 0x12, 0xe6, 0x5f, 0xc0, 0x5a, 0xde, 0x16, 0xcc, 0x39,
	0xf7, 0x00, 0x56, 0x5f, 0xce, 0xa2, 0x93, 0x7c, 0x09, 0x0c, 0x85, 0x03, 0x07, 0xe2, 0x82, 0xab,
	0xb1, 0xe3, 0x97, 0x83, 0xe0, 0xc0, 0x9a, 0x32, 0xda, 0xda, 0xb5, 0x12, 0xe6, 0x4f, 0x61, 0x55,
	0x37, 0x14, 0x75, 0x45, 0xa8, 0xcf, 0xaf, 0x52, 0x5b, 0x84, 0xf0, 0xfb, 0x9d, 0x8c, 0xf8, 0x4d,
	0x13, 0xa0, 0xe8, 0x3f, 0xe6, 0x86, 0xf5, 0x61, 0x5d, 0x87, 0xa1, 0x34, 0xe5, 0x12, 0x86, 0x27,
	0x95, 0x36, 0xf9, 0xd4, 0xf1, 0xc3, 0x85, 0xb0, 0x4e, 0x1b, 0xb2, 0xe4, 0x49, 0x19, 0x2c, 0xec,
	0x74, 0x9d, 0x85, 0x71, 0xa1, 0xc2, 0x4e, 0xd7, 0xd8, 0x59, 0x75, 0xed, 0x74, 0xab, 0x76, 0x76,
	0xc9, 0x4e, 0xcb, 0xb5, 0xb3, 0x5b, 0xb6, 0xb3, 0x6b, 0xec, 0xb4, 0x5d, 0x3b, 0x06, 0xf4, 0xff,
	0xd8, 0xa0, 0xd6, 0x23, 0x6f, 0xa7, 0xfe, 0xef, 0xd2, 0x34, 0x84, 0x65, 0x6c, 0xb4, 0xe6, 0xfc,
	0xda, 0xd6, 0x2d, 0x9f, 0x73, 0x24, 0xe4, 0xb4, 0xe5, 0x39, 0xf7, 0xf1, 0x9c, 0x46, 0x8f, 0x0f,
	0xe3, 0x8c, 0xaa, 0xb0, 0x3d, 0xaa, 0x0a, 0xc0, 0xff, 0x7b, 0x13, 0xa0, 0xe8, 0xee, 0xde, 0xd9,
	0xa0, 0x1e, 0xb4, 0x4c, 0x1a, 0xd8, 0xd3, 0xd1, 0x90, 0x45, 0x7a, 0x3f, 0x3d, 0xe6, 0x97, 0xf6,
	0xbe, 0x5b, 0x20, 0x45, 0x7a, 0x3f, 0xa5, 0xfb, 0xba, 0x49, 0x86, 0x12, 0x56, 0x58, 0xef, 0xda,
	0xd3, 0xc3, 0x90, 0x85, 0xf5, 0x2e, 0x5a, 0x6f, 0xbb, 0xd6, 0xbb, 0x25, 0xeb, 0x5d, 0x6d, 0x7d,
	0xcd, 0xb5, 0xde, 0xad, 0x58, 0xdf, 0x35, 0xf7, 0x33, 0x4b, 0xa2, 0x75, 0xdd, 0xc8, 0x38, 0x57,
	0x32, 0x07, 0xf1, 0xbf, 0x69, 0x40, 0xdb, 0xb6, 0xb9, 0x0b, 0xf3, 0xca, 0x6d, 0x1f, 0x8a, 0xcc,
	0x79, 0x64, 0x6a, 0xa7, 0x49, 0x5d, 0xb3, 0xdd, 0x1c, 0x88, 0x24, 0x54, 0x72, 0xc2, 0x4f, 0x64,
	0x28, 0xb3, 0x2b, 0x13, 0x56, 0x17, 0x2a, 0x2d, 0xc8, 0x4a, 0x79, 0x41, 0xfc, 0x7f, 0x35, 0xa0,
	0x6d, 0xfb, 0xe7, 0x39, 0xd7, 0x3c, 0x68, 0x0d, 0x12, 0xd7, 0x31, 0x4b, 0x1a, 0x8e, 0xb3, 0xc4,
	0x96, 0xc4, 0x48, 0xf6, 0x66, 0x4a, 0x89, 0x78, 0x74, 0x45, 0x8a, 0xa6, 0x0c, 0xb9, 0x18, 0xdd,
	0xb9, 0x0d, 0x4d, 0x93, 0x30, 0x5e, 0x95, 0x41, 0x74, 0xfb, 0x40, 0x09, 0x41, 0x31, 0xd5, 0xab,
	0x9d, 0xd3, 0x38, 0x8a, 0x0d, 0xa8, 0xb3, 0xed, 0x4b, 0x98, 0xff, 0xe7, 0x15, 0xe8, 0x38, 0x2d,
	0x7d, 0x5d, 0xe0, 0xdf, 0xa4, 0x42, 0xb9, 0x97, 0x85, 0x02, 0xd0, 0xcd, 0x66, 0x16, 0x0a, 0x77,
	0x43, 0xe7, 0x00, 0x75, 0x6e, 0x32, 0x0b, 0x29, 0x00, 0xb6, 0x73, 0x33, 0x34, 0x9e, 0x8b, 0xbd,
	0x59, 0x34, 0x0b, 0x79, 0x26, 0xcf, 0xa9, 0xf1, 0x34, 0xd3, 0xab, 0xa0, 0x65, 0x39, 0xba, 0xf8,
	0xae, 0x56, 0xe5, 0xe8, 0xde, 0x5b, 0x92, 0xc3, 0x2b, 0x90, 0x99, 0x6d, 0x05, 0xc5, 0x98, 0x98,
	0xce, 0x1f, 0x43, 0x94, 0x9a, 0x2c, 0x2f, 0x61, 0xd5, 0xea, 0xbd, 0x76, 0x8b, 0xea, 0x0d, 0xb7,
	0xa8, 0xde, 0x9d, 0x5b, 0x54, 0xef, 0xf5, 0x5b, 0x54, 0xef, 0x8d, 0x5b, 0x54, 0xef, 0xcd, 0x9a,
	0xea, 0xcd, 0xb6, 0x60, 0x09, 0x6f, 0x28, 0xba, 0x73, 0xc0, 0x4f, 0xca, 0x50, 0x6a, 0x49, 0x84,
	0xe9, 0x13, 0x2c, 0x89, 0x79, 0xd0, 0x7f, 0x6a, 0x3a, 0x83, 0x66, 0xff, 0x29, 0xd1, 0x5d, 0x8f,
	0x19, 0xba, 0x4b, 0xf4, 0xae, 0x77, 0xcf, 0xd0, 0xbb, 0x44, 0x3f, 0xf3, 0xee, 0x1b, 0xfa, 0x19,
	0xd1, 0x9f, 0x78, 0xef, 0x19, 0xfa, 0x13, 0xa2, 0x3f, 0xf5, 0x1e, 0x18, 0xfa, 0x53, 0xa2, 0x9f,
	0x7b, 0xef, 0x1b, 0xfa, 0x39, 0xd1, 0x9f, 0x79, 0x9e, 0xa1, 0x3f, 0x23, 0xfa, 0x73, 0xef, 0x03,
	0x43, 0x7f, 0xee, 0x47, 0xd0, 0x32, 0xcf, 0x46, 0xb5, 0x4f, 0x0b, 0x58, 0x7b, 0x28, 0x3b, 0xec,
	0xd3, 0x82, 0x05, 0x70, 0x8a, 0xc7, 0xfc, 0x92, 0x78, 0x66, 0x13, 0x1a, 0x12, 0xd3, 0x33, 0x6f,
	0x54, 0x4c, 0x7a, 0x5a, 0xda, 0xff, 0x4d, 0x03, 0xda, 0xf6, 0x95, 0xe9, 0x5b, 0xbe, 0x65, 0x30,
	0x58, 0x46, 0x4d, 0xfb, 0xb4, 0x83, 0xdf, 0xb8, 0x82, 0xf8, 0x5b, 0xee, 0x79, 0x5c, 0xc8, 0xae,
	0xcd, 0x4a, 0xbe, 0x36, 0xfe, 0x3f, 0x1a, 0xf9, 0xc3, 0xd6, 0xf0, 0x4c, 0xc6, 0x75, 0x75, 0xa7,
	0xc7, 0x15, 0xb2, 0x6c, 0xdd, 0x31, 0xa4, 0xe1, 0xb8, 0x75, 0xc7, 0x90, 0x58, 0x83, 0x7b, 0x5c,
	0x0d, 0x4a, 0xe7, 0x99, 0x83, 0xdc, 0xf0, 0xb4, 0xa4, 0xed, 0x3a, 0xa5, 0xc6, 0x92, 0xd8, 0x4e,
	0xb8, 0xaf, 0x28, 0x9a, 0xb0, 0x73, 0x6a, 0x17, 0x73, 0xfa, 0x67, 0x03, 0x96, 0x8f, 0x78, 0x54,
	0x7b, 0x54, 0x22, 0xee, 0xcc, 0x26, 0xa7, 0x2d, 0xcf, 0x3d, 0x2a, 0x2d, 0x4d, 0x25, 0x8e, 0x47,
	0xd3, 0xca, 0x8b, 0x59, 0x09, 0xbb, 0x61, 0x52, 0xc6, 0xba, 0x5b, 0x40, 0x2d, 0x7d, 0xdb, 0x69,
	0x75, 0xff, 0xd2, 0x80, 0xd6, 0xbe, 0xfe, 0x7b, 0x8d, 0xbd, 0x84, 0x15, 0xfa, 0x83, 0x8c, 0xd5,
	0xbe, 0x4c, 0xbb, 0xff, 0xaf, 0x6d, 0x7f, 0xef, 0x1a, 0x09, 0xfd, 0x1f, 0x97, 0xff, 0x1d, 0xf6,
	0x15, 0xac, 0xea, 0xff, 0xbd, 0x58, 0xad, 0x78, 0xe9, 0x9f, 0xb3, 0x6d, 0xff, 0x3a, 0x11, 0x6b,
	0xf2, 0x64, 0x95, 0xfe, 0x02, 0xdc, 0xfd, 0x5f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x97, 0x3b, 0xad,
	0x23, 0x21, 0x1c, 0x00, 0x00,
}
