// Code generated by protoc-gen-go. DO NOT EDIT.
// source: proto/example/example.proto

package go_micro_srv_data

import (
	fmt "fmt"
	proto "github.com/golang/protobuf/proto"
	math "math"
)

// Reference imports to suppress errors if they are not otherwise used.
var _ = proto.Marshal
var _ = fmt.Errorf
var _ = math.Inf

// This is a compile-time assertion to ensure that this generated file
// is compatible with the proto package it is being compiled against.
// A compilation error at this line likely means your copy of the
// proto package needs to be updated.
const _ = proto.ProtoPackageIsVersion2 // please upgrade the proto package

type Request struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Request) Reset()         { *m = Request{} }
func (m *Request) String() string { return proto.CompactTextString(m) }
func (*Request) ProtoMessage()    {}
func (*Request) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{0}
}

func (m *Request) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Request.Unmarshal(m, b)
}
func (m *Request) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Request.Marshal(b, m, deterministic)
}
func (m *Request) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Request.Merge(m, src)
}
func (m *Request) XXX_Size() int {
	return xxx_messageInfo_Request.Size(m)
}
func (m *Request) XXX_DiscardUnknown() {
	xxx_messageInfo_Request.DiscardUnknown(m)
}

var xxx_messageInfo_Request proto.InternalMessageInfo

func (m *Request) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type Response struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Response) Reset()         { *m = Response{} }
func (m *Response) String() string { return proto.CompactTextString(m) }
func (*Response) ProtoMessage()    {}
func (*Response) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{1}
}

func (m *Response) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Response.Unmarshal(m, b)
}
func (m *Response) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Response.Marshal(b, m, deterministic)
}
func (m *Response) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Response.Merge(m, src)
}
func (m *Response) XXX_Size() int {
	return xxx_messageInfo_Response.Size(m)
}
func (m *Response) XXX_DiscardUnknown() {
	xxx_messageInfo_Response.DiscardUnknown(m)
}

var xxx_messageInfo_Response proto.InternalMessageInfo

func (m *Response) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *Response) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//login的参数
type LoginLampRequest struct {
	Data                 []byte   `protobuf:"bytes,1,opt,name=data,proto3" json:"data,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginLampRequest) Reset()         { *m = LoginLampRequest{} }
func (m *LoginLampRequest) String() string { return proto.CompactTextString(m) }
func (*LoginLampRequest) ProtoMessage()    {}
func (*LoginLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{2}
}

func (m *LoginLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginLampRequest.Unmarshal(m, b)
}
func (m *LoginLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginLampRequest.Marshal(b, m, deterministic)
}
func (m *LoginLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginLampRequest.Merge(m, src)
}
func (m *LoginLampRequest) XXX_Size() int {
	return xxx_messageInfo_LoginLampRequest.Size(m)
}
func (m *LoginLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_LoginLampRequest proto.InternalMessageInfo

func (m *LoginLampRequest) GetData() []byte {
	if m != nil {
		return m.Data
	}
	return nil
}

type LoginLampResponse struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *LoginLampResponse) Reset()         { *m = LoginLampResponse{} }
func (m *LoginLampResponse) String() string { return proto.CompactTextString(m) }
func (*LoginLampResponse) ProtoMessage()    {}
func (*LoginLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{3}
}

func (m *LoginLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_LoginLampResponse.Unmarshal(m, b)
}
func (m *LoginLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_LoginLampResponse.Marshal(b, m, deterministic)
}
func (m *LoginLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_LoginLampResponse.Merge(m, src)
}
func (m *LoginLampResponse) XXX_Size() int {
	return xxx_messageInfo_LoginLampResponse.Size(m)
}
func (m *LoginLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_LoginLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_LoginLampResponse proto.InternalMessageInfo

func (m *LoginLampResponse) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *LoginLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *LoginLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type Data struct {
	MaxLevel             string   `protobuf:"bytes,1,opt,name=MaxLevel,proto3" json:"MaxLevel,omitempty"`
	CurrentLevel         string   `protobuf:"bytes,2,opt,name=CurrentLevel,proto3" json:"CurrentLevel,omitempty"`
	CurrentLampCode      string   `protobuf:"bytes,3,opt,name=CurrentLampCode,proto3" json:"CurrentLampCode,omitempty"`
	UserMoney            string   `protobuf:"bytes,4,opt,name=UserMoney,proto3" json:"UserMoney,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Data) Reset()         { *m = Data{} }
func (m *Data) String() string { return proto.CompactTextString(m) }
func (*Data) ProtoMessage()    {}
func (*Data) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{4}
}

func (m *Data) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Data.Unmarshal(m, b)
}
func (m *Data) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Data.Marshal(b, m, deterministic)
}
func (m *Data) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Data.Merge(m, src)
}
func (m *Data) XXX_Size() int {
	return xxx_messageInfo_Data.Size(m)
}
func (m *Data) XXX_DiscardUnknown() {
	xxx_messageInfo_Data.DiscardUnknown(m)
}

var xxx_messageInfo_Data proto.InternalMessageInfo

func (m *Data) GetMaxLevel() string {
	if m != nil {
		return m.MaxLevel
	}
	return ""
}

func (m *Data) GetCurrentLevel() string {
	if m != nil {
		return m.CurrentLevel
	}
	return ""
}

func (m *Data) GetCurrentLampCode() string {
	if m != nil {
		return m.CurrentLampCode
	}
	return ""
}

func (m *Data) GetUserMoney() string {
	if m != nil {
		return m.UserMoney
	}
	return ""
}

//Config方法的参数
type ConfigLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigLampRequest) Reset()         { *m = ConfigLampRequest{} }
func (m *ConfigLampRequest) String() string { return proto.CompactTextString(m) }
func (*ConfigLampRequest) ProtoMessage()    {}
func (*ConfigLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{5}
}

func (m *ConfigLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigLampRequest.Unmarshal(m, b)
}
func (m *ConfigLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigLampRequest.Marshal(b, m, deterministic)
}
func (m *ConfigLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigLampRequest.Merge(m, src)
}
func (m *ConfigLampRequest) XXX_Size() int {
	return xxx_messageInfo_ConfigLampRequest.Size(m)
}
func (m *ConfigLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigLampRequest proto.InternalMessageInfo

func (m *ConfigLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

type ConfigLampResponse struct {
	Datalist             *Data    `protobuf:"bytes,1,opt,name=datalist,proto3" json:"datalist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *ConfigLampResponse) Reset()         { *m = ConfigLampResponse{} }
func (m *ConfigLampResponse) String() string { return proto.CompactTextString(m) }
func (*ConfigLampResponse) ProtoMessage()    {}
func (*ConfigLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{6}
}

func (m *ConfigLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_ConfigLampResponse.Unmarshal(m, b)
}
func (m *ConfigLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_ConfigLampResponse.Marshal(b, m, deterministic)
}
func (m *ConfigLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_ConfigLampResponse.Merge(m, src)
}
func (m *ConfigLampResponse) XXX_Size() int {
	return xxx_messageInfo_ConfigLampResponse.Size(m)
}
func (m *ConfigLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_ConfigLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_ConfigLampResponse proto.InternalMessageInfo

func (m *ConfigLampResponse) GetDatalist() *Data {
	if m != nil {
		return m.Datalist
	}
	return nil
}

func (m *ConfigLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *ConfigLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

type New struct {
	Name                 string   `protobuf:"bytes,1,opt,name=name,proto3" json:"name,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	GetStatus            string   `protobuf:"bytes,3,opt,name=GetStatus,proto3" json:"GetStatus,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *New) Reset()         { *m = New{} }
func (m *New) String() string { return proto.CompactTextString(m) }
func (*New) ProtoMessage()    {}
func (*New) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{7}
}

func (m *New) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_New.Unmarshal(m, b)
}
func (m *New) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_New.Marshal(b, m, deterministic)
}
func (m *New) XXX_Merge(src proto.Message) {
	xxx_messageInfo_New.Merge(m, src)
}
func (m *New) XXX_Size() int {
	return xxx_messageInfo_New.Size(m)
}
func (m *New) XXX_DiscardUnknown() {
	xxx_messageInfo_New.DiscardUnknown(m)
}

var xxx_messageInfo_New proto.InternalMessageInfo

func (m *New) GetName() string {
	if m != nil {
		return m.Name
	}
	return ""
}

func (m *New) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

func (m *New) GetGetStatus() string {
	if m != nil {
		return m.GetStatus
	}
	return ""
}

type Lamp struct {
	LampId               string   `protobuf:"bytes,1,opt,name=LampId,proto3" json:"LampId,omitempty"`
	LampPrice            string   `protobuf:"bytes,2,opt,name=LampPrice,proto3" json:"LampPrice,omitempty"`
	LampUrl              string   `protobuf:"bytes,3,opt,name=LampUrl,proto3" json:"LampUrl,omitempty"`
	IsHave               string   `protobuf:"bytes,4,opt,name=IsHave,proto3" json:"IsHave,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *Lamp) Reset()         { *m = Lamp{} }
func (m *Lamp) String() string { return proto.CompactTextString(m) }
func (*Lamp) ProtoMessage()    {}
func (*Lamp) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{8}
}

func (m *Lamp) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_Lamp.Unmarshal(m, b)
}
func (m *Lamp) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_Lamp.Marshal(b, m, deterministic)
}
func (m *Lamp) XXX_Merge(src proto.Message) {
	xxx_messageInfo_Lamp.Merge(m, src)
}
func (m *Lamp) XXX_Size() int {
	return xxx_messageInfo_Lamp.Size(m)
}
func (m *Lamp) XXX_DiscardUnknown() {
	xxx_messageInfo_Lamp.DiscardUnknown(m)
}

var xxx_messageInfo_Lamp proto.InternalMessageInfo

func (m *Lamp) GetLampId() string {
	if m != nil {
		return m.LampId
	}
	return ""
}

func (m *Lamp) GetLampPrice() string {
	if m != nil {
		return m.LampPrice
	}
	return ""
}

func (m *Lamp) GetLampUrl() string {
	if m != nil {
		return m.LampUrl
	}
	return ""
}

func (m *Lamp) GetIsHave() string {
	if m != nil {
		return m.IsHave
	}
	return ""
}

//拉取邀请新人列表服务参数
type PullNewLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Url                  string   `protobuf:"bytes,2,opt,name=url,proto3" json:"url,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullNewLampRequest) Reset()         { *m = PullNewLampRequest{} }
func (m *PullNewLampRequest) String() string { return proto.CompactTextString(m) }
func (*PullNewLampRequest) ProtoMessage()    {}
func (*PullNewLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{9}
}

func (m *PullNewLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullNewLampRequest.Unmarshal(m, b)
}
func (m *PullNewLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullNewLampRequest.Marshal(b, m, deterministic)
}
func (m *PullNewLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullNewLampRequest.Merge(m, src)
}
func (m *PullNewLampRequest) XXX_Size() int {
	return xxx_messageInfo_PullNewLampRequest.Size(m)
}
func (m *PullNewLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_PullNewLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_PullNewLampRequest proto.InternalMessageInfo

func (m *PullNewLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *PullNewLampRequest) GetUrl() string {
	if m != nil {
		return m.Url
	}
	return ""
}

type PullNewLampResponse struct {
	Newlist              []*New   `protobuf:"bytes,1,rep,name=newlist,proto3" json:"newlist,omitempty"`
	UserMoney            string   `protobuf:"bytes,2,opt,name=UserMoney,proto3" json:"UserMoney,omitempty"`
	Errno                string   `protobuf:"bytes,3,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,4,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *PullNewLampResponse) Reset()         { *m = PullNewLampResponse{} }
func (m *PullNewLampResponse) String() string { return proto.CompactTextString(m) }
func (*PullNewLampResponse) ProtoMessage()    {}
func (*PullNewLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{10}
}

func (m *PullNewLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_PullNewLampResponse.Unmarshal(m, b)
}
func (m *PullNewLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_PullNewLampResponse.Marshal(b, m, deterministic)
}
func (m *PullNewLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_PullNewLampResponse.Merge(m, src)
}
func (m *PullNewLampResponse) XXX_Size() int {
	return xxx_messageInfo_PullNewLampResponse.Size(m)
}
func (m *PullNewLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_PullNewLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_PullNewLampResponse proto.InternalMessageInfo

func (m *PullNewLampResponse) GetNewlist() []*New {
	if m != nil {
		return m.Newlist
	}
	return nil
}

func (m *PullNewLampResponse) GetUserMoney() string {
	if m != nil {
		return m.UserMoney
	}
	return ""
}

func (m *PullNewLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *PullNewLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//金币变化服务
type GoldLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Type                 string   `protobuf:"bytes,2,opt,name=type,proto3" json:"type,omitempty"`
	Number               string   `protobuf:"bytes,3,opt,name=number,proto3" json:"number,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoldLampRequest) Reset()         { *m = GoldLampRequest{} }
func (m *GoldLampRequest) String() string { return proto.CompactTextString(m) }
func (*GoldLampRequest) ProtoMessage()    {}
func (*GoldLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{11}
}

func (m *GoldLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoldLampRequest.Unmarshal(m, b)
}
func (m *GoldLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoldLampRequest.Marshal(b, m, deterministic)
}
func (m *GoldLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoldLampRequest.Merge(m, src)
}
func (m *GoldLampRequest) XXX_Size() int {
	return xxx_messageInfo_GoldLampRequest.Size(m)
}
func (m *GoldLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GoldLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GoldLampRequest proto.InternalMessageInfo

func (m *GoldLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *GoldLampRequest) GetType() string {
	if m != nil {
		return m.Type
	}
	return ""
}

func (m *GoldLampRequest) GetNumber() string {
	if m != nil {
		return m.Number
	}
	return ""
}

type GoldLampResponse struct {
	Newlist              []*New   `protobuf:"bytes,1,rep,name=newlist,proto3" json:"newlist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GoldLampResponse) Reset()         { *m = GoldLampResponse{} }
func (m *GoldLampResponse) String() string { return proto.CompactTextString(m) }
func (*GoldLampResponse) ProtoMessage()    {}
func (*GoldLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{12}
}

func (m *GoldLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GoldLampResponse.Unmarshal(m, b)
}
func (m *GoldLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GoldLampResponse.Marshal(b, m, deterministic)
}
func (m *GoldLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GoldLampResponse.Merge(m, src)
}
func (m *GoldLampResponse) XXX_Size() int {
	return xxx_messageInfo_GoldLampResponse.Size(m)
}
func (m *GoldLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GoldLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GoldLampResponse proto.InternalMessageInfo

func (m *GoldLampResponse) GetNewlist() []*New {
	if m != nil {
		return m.Newlist
	}
	return nil
}

func (m *GoldLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *GoldLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//服务器排名服务
type RankingLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankingLampRequest) Reset()         { *m = RankingLampRequest{} }
func (m *RankingLampRequest) String() string { return proto.CompactTextString(m) }
func (*RankingLampRequest) ProtoMessage()    {}
func (*RankingLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{13}
}

func (m *RankingLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingLampRequest.Unmarshal(m, b)
}
func (m *RankingLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingLampRequest.Marshal(b, m, deterministic)
}
func (m *RankingLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingLampRequest.Merge(m, src)
}
func (m *RankingLampRequest) XXX_Size() int {
	return xxx_messageInfo_RankingLampRequest.Size(m)
}
func (m *RankingLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_RankingLampRequest proto.InternalMessageInfo

func (m *RankingLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

type RankingLampResponse struct {
	Newlist              []*New   `protobuf:"bytes,1,rep,name=newlist,proto3" json:"newlist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *RankingLampResponse) Reset()         { *m = RankingLampResponse{} }
func (m *RankingLampResponse) String() string { return proto.CompactTextString(m) }
func (*RankingLampResponse) ProtoMessage()    {}
func (*RankingLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{14}
}

func (m *RankingLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_RankingLampResponse.Unmarshal(m, b)
}
func (m *RankingLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_RankingLampResponse.Marshal(b, m, deterministic)
}
func (m *RankingLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_RankingLampResponse.Merge(m, src)
}
func (m *RankingLampResponse) XXX_Size() int {
	return xxx_messageInfo_RankingLampResponse.Size(m)
}
func (m *RankingLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_RankingLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_RankingLampResponse proto.InternalMessageInfo

func (m *RankingLampResponse) GetNewlist() []*New {
	if m != nil {
		return m.Newlist
	}
	return nil
}

func (m *RankingLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *RankingLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//关卡服务
type CheckpointLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointLampRequest) Reset()         { *m = CheckpointLampRequest{} }
func (m *CheckpointLampRequest) String() string { return proto.CompactTextString(m) }
func (*CheckpointLampRequest) ProtoMessage()    {}
func (*CheckpointLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{15}
}

func (m *CheckpointLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointLampRequest.Unmarshal(m, b)
}
func (m *CheckpointLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointLampRequest.Marshal(b, m, deterministic)
}
func (m *CheckpointLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointLampRequest.Merge(m, src)
}
func (m *CheckpointLampRequest) XXX_Size() int {
	return xxx_messageInfo_CheckpointLampRequest.Size(m)
}
func (m *CheckpointLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointLampRequest proto.InternalMessageInfo

func (m *CheckpointLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *CheckpointLampRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type CheckpointLampResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *CheckpointLampResponse) Reset()         { *m = CheckpointLampResponse{} }
func (m *CheckpointLampResponse) String() string { return proto.CompactTextString(m) }
func (*CheckpointLampResponse) ProtoMessage()    {}
func (*CheckpointLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{16}
}

func (m *CheckpointLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_CheckpointLampResponse.Unmarshal(m, b)
}
func (m *CheckpointLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_CheckpointLampResponse.Marshal(b, m, deterministic)
}
func (m *CheckpointLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_CheckpointLampResponse.Merge(m, src)
}
func (m *CheckpointLampResponse) XXX_Size() int {
	return xxx_messageInfo_CheckpointLampResponse.Size(m)
}
func (m *CheckpointLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_CheckpointLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_CheckpointLampResponse proto.InternalMessageInfo

func (m *CheckpointLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *CheckpointLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//设置灯服务
type SetLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLampRequest) Reset()         { *m = SetLampRequest{} }
func (m *SetLampRequest) String() string { return proto.CompactTextString(m) }
func (*SetLampRequest) ProtoMessage()    {}
func (*SetLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{17}
}

func (m *SetLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLampRequest.Unmarshal(m, b)
}
func (m *SetLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLampRequest.Marshal(b, m, deterministic)
}
func (m *SetLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLampRequest.Merge(m, src)
}
func (m *SetLampRequest) XXX_Size() int {
	return xxx_messageInfo_SetLampRequest.Size(m)
}
func (m *SetLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_SetLampRequest proto.InternalMessageInfo

func (m *SetLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *SetLampRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type SetLampResponse struct {
	Errno                string   `protobuf:"bytes,1,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,2,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *SetLampResponse) Reset()         { *m = SetLampResponse{} }
func (m *SetLampResponse) String() string { return proto.CompactTextString(m) }
func (*SetLampResponse) ProtoMessage()    {}
func (*SetLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{18}
}

func (m *SetLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_SetLampResponse.Unmarshal(m, b)
}
func (m *SetLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_SetLampResponse.Marshal(b, m, deterministic)
}
func (m *SetLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_SetLampResponse.Merge(m, src)
}
func (m *SetLampResponse) XXX_Size() int {
	return xxx_messageInfo_SetLampResponse.Size(m)
}
func (m *SetLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_SetLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_SetLampResponse proto.InternalMessageInfo

func (m *SetLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *SetLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//获取灯列表服务
type GetLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLampRequest) Reset()         { *m = GetLampRequest{} }
func (m *GetLampRequest) String() string { return proto.CompactTextString(m) }
func (*GetLampRequest) ProtoMessage()    {}
func (*GetLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{19}
}

func (m *GetLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLampRequest.Unmarshal(m, b)
}
func (m *GetLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLampRequest.Marshal(b, m, deterministic)
}
func (m *GetLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLampRequest.Merge(m, src)
}
func (m *GetLampRequest) XXX_Size() int {
	return xxx_messageInfo_GetLampRequest.Size(m)
}
func (m *GetLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_GetLampRequest proto.InternalMessageInfo

func (m *GetLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

type GetLampResponse struct {
	Lamplist             []*Lamp  `protobuf:"bytes,1,rep,name=lamplist,proto3" json:"lamplist,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *GetLampResponse) Reset()         { *m = GetLampResponse{} }
func (m *GetLampResponse) String() string { return proto.CompactTextString(m) }
func (*GetLampResponse) ProtoMessage()    {}
func (*GetLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{20}
}

func (m *GetLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_GetLampResponse.Unmarshal(m, b)
}
func (m *GetLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_GetLampResponse.Marshal(b, m, deterministic)
}
func (m *GetLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_GetLampResponse.Merge(m, src)
}
func (m *GetLampResponse) XXX_Size() int {
	return xxx_messageInfo_GetLampResponse.Size(m)
}
func (m *GetLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_GetLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_GetLampResponse proto.InternalMessageInfo

func (m *GetLampResponse) GetLamplist() []*Lamp {
	if m != nil {
		return m.Lamplist
	}
	return nil
}

func (m *GetLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *GetLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

//购买灯服务
type BuyLampRequest struct {
	Skey                 string   `protobuf:"bytes,1,opt,name=skey,proto3" json:"skey,omitempty"`
	Code                 string   `protobuf:"bytes,2,opt,name=code,proto3" json:"code,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyLampRequest) Reset()         { *m = BuyLampRequest{} }
func (m *BuyLampRequest) String() string { return proto.CompactTextString(m) }
func (*BuyLampRequest) ProtoMessage()    {}
func (*BuyLampRequest) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{21}
}

func (m *BuyLampRequest) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyLampRequest.Unmarshal(m, b)
}
func (m *BuyLampRequest) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyLampRequest.Marshal(b, m, deterministic)
}
func (m *BuyLampRequest) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyLampRequest.Merge(m, src)
}
func (m *BuyLampRequest) XXX_Size() int {
	return xxx_messageInfo_BuyLampRequest.Size(m)
}
func (m *BuyLampRequest) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyLampRequest.DiscardUnknown(m)
}

var xxx_messageInfo_BuyLampRequest proto.InternalMessageInfo

func (m *BuyLampRequest) GetSkey() string {
	if m != nil {
		return m.Skey
	}
	return ""
}

func (m *BuyLampRequest) GetCode() string {
	if m != nil {
		return m.Code
	}
	return ""
}

type BuyLampResponse struct {
	UserMoney            string   `protobuf:"bytes,1,opt,name=UserMoney,proto3" json:"UserMoney,omitempty"`
	Errno                string   `protobuf:"bytes,2,opt,name=Errno,proto3" json:"Errno,omitempty"`
	Errmsg               string   `protobuf:"bytes,3,opt,name=Errmsg,proto3" json:"Errmsg,omitempty"`
	XXX_NoUnkeyedLiteral struct{} `json:"-"`
	XXX_unrecognized     []byte   `json:"-"`
	XXX_sizecache        int32    `json:"-"`
}

func (m *BuyLampResponse) Reset()         { *m = BuyLampResponse{} }
func (m *BuyLampResponse) String() string { return proto.CompactTextString(m) }
func (*BuyLampResponse) ProtoMessage()    {}
func (*BuyLampResponse) Descriptor() ([]byte, []int) {
	return fileDescriptor_097b3f5db5cf5789, []int{22}
}

func (m *BuyLampResponse) XXX_Unmarshal(b []byte) error {
	return xxx_messageInfo_BuyLampResponse.Unmarshal(m, b)
}
func (m *BuyLampResponse) XXX_Marshal(b []byte, deterministic bool) ([]byte, error) {
	return xxx_messageInfo_BuyLampResponse.Marshal(b, m, deterministic)
}
func (m *BuyLampResponse) XXX_Merge(src proto.Message) {
	xxx_messageInfo_BuyLampResponse.Merge(m, src)
}
func (m *BuyLampResponse) XXX_Size() int {
	return xxx_messageInfo_BuyLampResponse.Size(m)
}
func (m *BuyLampResponse) XXX_DiscardUnknown() {
	xxx_messageInfo_BuyLampResponse.DiscardUnknown(m)
}

var xxx_messageInfo_BuyLampResponse proto.InternalMessageInfo

func (m *BuyLampResponse) GetUserMoney() string {
	if m != nil {
		return m.UserMoney
	}
	return ""
}

func (m *BuyLampResponse) GetErrno() string {
	if m != nil {
		return m.Errno
	}
	return ""
}

func (m *BuyLampResponse) GetErrmsg() string {
	if m != nil {
		return m.Errmsg
	}
	return ""
}

func init() {
	proto.RegisterType((*Request)(nil), "go.micro.srv.data.Request")
	proto.RegisterType((*Response)(nil), "go.micro.srv.data.Response")
	proto.RegisterType((*LoginLampRequest)(nil), "go.micro.srv.data.LoginLampRequest")
	proto.RegisterType((*LoginLampResponse)(nil), "go.micro.srv.data.LoginLampResponse")
	proto.RegisterType((*Data)(nil), "go.micro.srv.data.data")
	proto.RegisterType((*ConfigLampRequest)(nil), "go.micro.srv.data.ConfigLampRequest")
	proto.RegisterType((*ConfigLampResponse)(nil), "go.micro.srv.data.ConfigLampResponse")
	proto.RegisterType((*New)(nil), "go.micro.srv.data.new")
	proto.RegisterType((*Lamp)(nil), "go.micro.srv.data.lamp")
	proto.RegisterType((*PullNewLampRequest)(nil), "go.micro.srv.data.PullNewLampRequest")
	proto.RegisterType((*PullNewLampResponse)(nil), "go.micro.srv.data.PullNewLampResponse")
	proto.RegisterType((*GoldLampRequest)(nil), "go.micro.srv.data.GoldLampRequest")
	proto.RegisterType((*GoldLampResponse)(nil), "go.micro.srv.data.GoldLampResponse")
	proto.RegisterType((*RankingLampRequest)(nil), "go.micro.srv.data.RankingLampRequest")
	proto.RegisterType((*RankingLampResponse)(nil), "go.micro.srv.data.RankingLampResponse")
	proto.RegisterType((*CheckpointLampRequest)(nil), "go.micro.srv.data.CheckpointLampRequest")
	proto.RegisterType((*CheckpointLampResponse)(nil), "go.micro.srv.data.CheckpointLampResponse")
	proto.RegisterType((*SetLampRequest)(nil), "go.micro.srv.data.SetLampRequest")
	proto.RegisterType((*SetLampResponse)(nil), "go.micro.srv.data.SetLampResponse")
	proto.RegisterType((*GetLampRequest)(nil), "go.micro.srv.data.GetLampRequest")
	proto.RegisterType((*GetLampResponse)(nil), "go.micro.srv.data.GetLampResponse")
	proto.RegisterType((*BuyLampRequest)(nil), "go.micro.srv.data.BuyLampRequest")
	proto.RegisterType((*BuyLampResponse)(nil), "go.micro.srv.data.BuyLampResponse")
}

func init() { proto.RegisterFile("proto/example/example.proto", fileDescriptor_097b3f5db5cf5789) }

var fileDescriptor_097b3f5db5cf5789 = []byte{
	// 752 bytes of a gzipped FileDescriptorProto
	0x1f, 0x8b, 0x08, 0x00, 0x00, 0x00, 0x00, 0x00, 0x02, 0xff, 0xbc, 0x56, 0x4d, 0x6f, 0xd3, 0x4c,
	0x10, 0x6e, 0x1a, 0xbf, 0x4d, 0x3a, 0xad, 0x92, 0x76, 0xfb, 0x52, 0x22, 0x17, 0x24, 0xd8, 0x7e,
	0x10, 0x2e, 0x01, 0xb5, 0x97, 0x8a, 0x4b, 0x05, 0xa1, 0x98, 0x4a, 0x2d, 0x2a, 0xae, 0x22, 0x21,
	0x21, 0x90, 0xdc, 0x64, 0x09, 0x56, 0xec, 0xb5, 0x59, 0xdb, 0x49, 0xf3, 0x27, 0xb8, 0xf0, 0x83,
	0x41, 0x6b, 0xaf, 0x3f, 0xb3, 0xc4, 0x4d, 0x0e, 0x5c, 0xda, 0x9d, 0xf1, 0xb3, 0xcf, 0xcc, 0x3c,
	0xbb, 0x33, 0x1b, 0xd8, 0x73, 0x99, 0xe3, 0x3b, 0x2f, 0xc8, 0x9d, 0x61, 0xbb, 0x16, 0x89, 0xff,
	0x77, 0x42, 0x2f, 0xda, 0x1e, 0x3a, 0x1d, 0xdb, 0xec, 0x33, 0xa7, 0xe3, 0xb1, 0x71, 0x67, 0x60,
	0xf8, 0x06, 0x7e, 0x0c, 0x35, 0x9d, 0xfc, 0x08, 0x88, 0xe7, 0x23, 0x04, 0x0a, 0x77, 0xb5, 0x2a,
	0x4f, 0x2a, 0xed, 0x4d, 0x3d, 0x5c, 0xe3, 0x53, 0xa8, 0xeb, 0xc4, 0x73, 0x1d, 0xea, 0x11, 0xf4,
	0x3f, 0xfc, 0x77, 0xce, 0x18, 0x75, 0x42, 0xc0, 0xba, 0x1e, 0x19, 0x68, 0x17, 0xd6, 0xce, 0x19,
	0xb3, 0xbd, 0x61, 0x6b, 0x35, 0x74, 0x0b, 0x0b, 0x1f, 0xc1, 0xd6, 0xa5, 0x33, 0x34, 0xe9, 0xa5,
	0x61, 0xbb, 0xf3, 0x22, 0xf4, 0x60, 0x3b, 0x83, 0x13, 0xa1, 0x10, 0x28, 0xde, 0x88, 0x4c, 0x45,
	0xa4, 0x70, 0x9d, 0x86, 0x5f, 0x95, 0x87, 0xaf, 0xe6, 0xc2, 0xff, 0xac, 0x44, 0xb1, 0x90, 0x0a,
	0xf5, 0x2b, 0xe3, 0xee, 0x92, 0x8c, 0x89, 0x25, 0xe8, 0x12, 0x1b, 0x61, 0xd8, 0xec, 0x06, 0x8c,
	0x11, 0xea, 0x47, 0xdf, 0x23, 0xe6, 0x9c, 0x0f, 0xb5, 0xa1, 0x19, 0xdb, 0x86, 0xed, 0x76, 0x9d,
	0x01, 0x11, 0x91, 0x8a, 0x6e, 0xf4, 0x08, 0xd6, 0x7b, 0x1e, 0x61, 0x57, 0x0e, 0x25, 0xd3, 0x96,
	0x12, 0x62, 0x52, 0x07, 0x7e, 0x06, 0xdb, 0x5d, 0x87, 0x7e, 0x33, 0x87, 0x05, 0x41, 0x8a, 0x75,
	0xe2, 0x09, 0xa0, 0x2c, 0x50, 0x28, 0x72, 0x02, 0x75, 0x5e, 0x8e, 0x65, 0x7a, 0x7e, 0x88, 0xde,
	0x38, 0x7e, 0xd8, 0x99, 0x39, 0xcd, 0xf0, 0x8f, 0x9e, 0x00, 0x17, 0x94, 0xec, 0x02, 0xaa, 0x94,
	0x4c, 0x78, 0x4e, 0xd4, 0xb0, 0x49, 0x9c, 0x13, 0x5f, 0xa3, 0x2d, 0xa8, 0x06, 0x2c, 0xd6, 0x87,
	0x2f, 0x79, 0xb1, 0x1a, 0xf1, 0x6f, 0x7c, 0xc3, 0x0f, 0x3c, 0xc1, 0x93, 0x3a, 0x30, 0x05, 0xc5,
	0x32, 0x6c, 0x97, 0x87, 0xe2, 0x55, 0x5c, 0x0c, 0x04, 0x9b, 0xb0, 0xf8, 0x6e, 0xbe, 0xba, 0x66,
	0x66, 0x9f, 0x08, 0xd6, 0xd4, 0x81, 0x5a, 0x50, 0xe3, 0x46, 0x8f, 0x59, 0x82, 0x39, 0x36, 0x39,
	0xdf, 0x85, 0xf7, 0xde, 0x18, 0x13, 0xa1, 0xaf, 0xb0, 0xf0, 0x2b, 0x40, 0xd7, 0x81, 0x65, 0x7d,
	0x20, 0x93, 0x12, 0x75, 0x67, 0x2b, 0xc1, 0xbf, 0x2a, 0xb0, 0x93, 0xdb, 0x2c, 0x14, 0x7f, 0x09,
	0x35, 0x4a, 0x26, 0x42, 0xf0, 0x6a, 0x7b, 0xe3, 0x78, 0x57, 0x22, 0x38, 0x25, 0x13, 0x3d, 0x86,
	0xe5, 0x2f, 0xc0, 0x6a, 0xe1, 0x02, 0xa4, 0x87, 0x51, 0x95, 0x1f, 0x86, 0x92, 0x3b, 0x8c, 0x8f,
	0xd0, 0xd4, 0x1c, 0x6b, 0x50, 0x56, 0x0e, 0x02, 0xc5, 0x9f, 0xba, 0xb1, 0x86, 0xe1, 0x9a, 0x53,
	0xd2, 0xc0, 0xbe, 0x25, 0x2c, 0x3e, 0xdf, 0xc8, 0xc2, 0x0c, 0xb6, 0x52, 0xca, 0xa5, 0x8b, 0x5c,
	0xec, 0x4e, 0xb5, 0x01, 0xe9, 0x06, 0x1d, 0x99, 0xb4, 0xf4, 0xda, 0x07, 0xb0, 0x93, 0x43, 0xfe,
	0xa3, 0x04, 0xcf, 0xe0, 0x41, 0xf7, 0x3b, 0xe9, 0x8f, 0x5c, 0xc7, 0x8c, 0x5a, 0xb9, 0x44, 0xed,
	0x3e, 0x1f, 0x00, 0x42, 0x6d, 0xbe, 0xc6, 0xef, 0x60, 0xb7, 0x48, 0xb0, 0xd4, 0xbc, 0x3c, 0x85,
	0xc6, 0x0d, 0x59, 0x2a, 0x83, 0x33, 0x68, 0x26, 0x3b, 0x97, 0x0a, 0x7d, 0x00, 0x0d, 0xad, 0x34,
	0x34, 0xf6, 0xa1, 0xa9, 0x15, 0xc2, 0x9c, 0x40, 0x9d, 0xb7, 0x79, 0xe6, 0x74, 0x64, 0x43, 0x89,
	0x43, 0xf4, 0x04, 0xb8, 0xe0, 0xf9, 0x9c, 0x42, 0xe3, 0x4d, 0x30, 0x5d, 0x46, 0x96, 0x2f, 0xd0,
	0x4c, 0x76, 0x8a, 0x7c, 0x73, 0x0d, 0x5a, 0xf9, 0x6b, 0x83, 0xde, 0x27, 0xb1, 0xe3, 0xdf, 0x6b,
	0x50, 0x3b, 0x8f, 0x5e, 0x57, 0xf4, 0x1a, 0x94, 0xb7, 0xe1, 0x5b, 0x23, 0xa9, 0x5e, 0xa4, 0xad,
	0xee, 0x49, 0xbf, 0x45, 0x89, 0xe1, 0x15, 0xf4, 0x09, 0xd6, 0x93, 0x67, 0x10, 0xed, 0x4b, 0xb0,
	0xc5, 0xc7, 0x54, 0x3d, 0x98, 0x0f, 0x4a, 0x98, 0xbf, 0xc2, 0x46, 0x66, 0xbc, 0xa1, 0x43, 0xc9,
	0xb6, 0xd9, 0xd9, 0xa9, 0x1e, 0x95, 0xc1, 0x12, 0xfe, 0xcf, 0x00, 0xe9, 0x7b, 0x85, 0x64, 0x59,
	0xcd, 0xbc, 0x7b, 0xea, 0x61, 0x09, 0x2a, 0x21, 0xef, 0x41, 0x3d, 0x9e, 0x59, 0x08, 0x4b, 0x36,
	0x15, 0x66, 0xa4, 0xba, 0x3f, 0x17, 0x93, 0xd5, 0x24, 0x33, 0x6c, 0xa4, 0x9a, 0xcc, 0x8e, 0x2d,
	0xa9, 0x26, 0x92, 0x99, 0x85, 0x57, 0xd0, 0x10, 0x1a, 0xf9, 0xa1, 0x80, 0xda, 0xb2, 0x8a, 0x65,
	0x83, 0x47, 0x7d, 0x7e, 0x0f, 0x64, 0x12, 0x48, 0x87, 0x9a, 0xe8, 0x7d, 0xf4, 0x54, 0xb2, 0x2f,
	0x3f, 0x51, 0x54, 0x3c, 0x0f, 0x92, 0xe5, 0xd4, 0xe6, 0x70, 0x6a, 0xe5, 0x9c, 0x9a, 0x8c, 0x53,
	0x34, 0xa3, 0x94, 0x33, 0xdf, 0xe2, 0x52, 0xce, 0x42, 0x2f, 0xe3, 0x95, 0xdb, 0xb5, 0xf0, 0x47,
	0xed, 0xc9, 0x9f, 0x00, 0x00, 0x00, 0xff, 0xff, 0x46, 0xb8, 0x59, 0x6a, 0xf3, 0x0a, 0x00, 0x00,
}
